import { SITE_NAME } from "@/lib/constants";

export interface Category {
  slug: string;
  label: string;
  icon: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
}

export const CATEGORIES: Category[] = [
  {
    slug: "text-writing",
    label: "Text & Writing",
    icon: "✍️",
    description: "Writing assistants, grammar checkers, markdown editors, and text analysis tools.",
    seoTitle: `Text & Writing Tools`,
    seoDescription: `Free online text and writing tools for ${SITE_NAME}. Markdown editors, text diff checkers, and more to supercharge your writing workflow.`,
  },
  {
    slug: "image-design",
    label: "Image & Design",
    icon: "🎨",
    description: "Image editors, color palette generators, CSS gradient tools, and design utilities.",
    seoTitle: `Image & Design Tools`,
    seoDescription: `Free online image and design tools for ${SITE_NAME}. Color palette generators, image optimizers, CSS gradient tools, and design resources.`,
  },
  {
    slug: "code-dev",
    label: "Code & Development",
    icon: "💻",
    description: "Code formatters, regex builders, API testers, JSON tools, and developer utilities.",
    seoTitle: `Developer Tools`,
    seoDescription: `Free online developer tools for ${SITE_NAME}. JSON formatters, regex builders, API testers, and code utilities for developers.`,
  },
  {
    slug: "data-analytics",
    label: "Data & Analytics",
    icon: "📊",
    description: "SQL builders, chart makers, data visualization, and analytics tools.",
    seoTitle: `Data & Analytics Tools`,
    seoDescription: `Free online data and analytics tools for ${SITE_NAME}. SQL query builders, chart makers, and data visualization utilities.`,
  },
  {
    slug: "audio-video",
    label: "Audio & Video",
    icon: "🎵",
    description: "Audio converters, video editors, media tools, and multimedia utilities.",
    seoTitle: `Audio & Video Tools`,
    seoDescription: `Free online audio and video tools for ${SITE_NAME}. Audio converters, media editors, and multimedia processing utilities.`,
  },
  {
    slug: "productivity",
    label: "Productivity",
    icon: "⚡",
    description: "IP tools, timers, and utilities that help you work smarter and faster.",
    seoTitle: `Productivity Tools`,
    seoDescription: `Free online productivity tools for ${SITE_NAME}. IP lookup, timers, and utilities designed to help you work smarter.`,
  },
  {
    slug: "network-internet",
    label: "Network & Internet",
    icon: "🌐",
    description: "WHOIS lookup, DNS tools, SSL checkers, and network diagnostic utilities.",
    seoTitle: `Network & Internet Tools`,
    seoDescription: `Free online network and internet tools for ${SITE_NAME}. WHOIS lookup, DNS checkers, SSL certificate validators, and network diagnostics.`,
  },
  {
    slug: "finance",
    label: "Finance",
    icon: "💰",
    description: "Mortgage calculators, loan calculators, budgeting tools, and financial planning utilities.",
    seoTitle: `Finance Tools`,
    seoDescription: `Free online finance tools for ${SITE_NAME}. Mortgage calculators, loan amortization, compound interest, salary converters, and financial planning utilities.`,
  },
  {
    slug: "calculators",
    label: "Calculators",
    icon: "🧮",
    description: "BMI calculators, calorie counters, age calculators, date calculators, and general math utilities.",
    seoTitle: `Online Calculators`,
    seoDescription: `Free online calculators for ${SITE_NAME}. BMI, calorie, age, date, time, unit, scientific, and general math calculators for everyday use.`,
  },
  {
    slug: "security",
    label: "Security",
    icon: "🔒",
    description: "Password strength checkers, breach checkers, CSRF generators, SSL tests, and security scanners.",
    seoTitle: `Security Tools`,
    seoDescription: `Free online security tools for ${SITE_NAME}. Password strength checkers, data breach checks, SSL testers, CSP validators, and XSS scanners.`,
  },
  {
    slug: "ai",
    label: "AI",
    icon: "🤖",
    description: "AI text summarizers, rewriters, grammar checkers, sentiment analyzers, and content generation tools.",
    seoTitle: `AI Tools`,
    seoDescription: `Free online AI tools for ${SITE_NAME}. Text summarization, rewriting, grammar checking, sentiment analysis, keyword extraction, and plagiarism detection.`,
  },
  {
    slug: "seo",
    label: "SEO",
    icon: "📈",
    description: "Keyword density checkers, SEO audits, page speed tests, backlink checkers, and SERP preview tools.",
    seoTitle: `SEO Tools`,
    seoDescription: `Free online SEO tools for ${SITE_NAME}. Keyword density analyzers, SEO audits, SERP previews, backlink checkers, and page speed testers.`,
  },
  {
    slug: "converters",
    label: "Converters",
    icon: "🔄",
    description: "CSV, JSON, XML, YAML, Markdown, HTML, and image format converters for data transformation.",
    seoTitle: `File & Data Converters`,
    seoDescription: `Free online converters for ${SITE_NAME}. CSV to JSON, JSON to XML, Markdown to HTML, image format converters, and data transformation tools.`,
  },
  {
    slug: "marketing",
    label: "Marketing",
    icon: "📣",
    description: "SEO tools, social media schedulers, email marketing platforms, analytics dashboards, and growth marketing utilities.",
    seoTitle: `Marketing Tools`,
    seoDescription: `Free online marketing tools for ${SITE_NAME}. SEO analyzers, social media schedulers, email marketing utilities, and growth hacking tools.`,
  },
  {
    slug: "writing",
    label: "Writing",
    icon: "✏️",
    description: "Grammar checkers, plagiarism detectors, readability analyzers, AI writing assistants, and editing utilities.",
    seoTitle: `Writing Tools`,
    seoDescription: `Free online writing tools for ${SITE_NAME}. Grammar checkers, plagiarism detectors, AI writing assistants, and editing utilities for better content.`,
  },
  {
    slug: "coding",
    label: "Coding",
    icon: "⌨️",
    description: "Code formatters, linters, compilers, validators, and debugging tools for JavaScript, Python, HTML, CSS, and more.",
    seoTitle: `Coding Tools`,
    seoDescription: `Free online coding tools for ${SITE_NAME}. Code formatters, compilers, validators, linters, and debugging utilities for every programming language.`,
  },
  {
    slug: "data",
    label: "Data",
    icon: "📊",
    description: "JSON editors, CSV processors, SQL builders, Excel utilities, data visualization, and ETL tools.",
    seoTitle: `Data Tools`,
    seoDescription: `Free online data tools for ${SITE_NAME}. JSON editors, CSV processors, SQL query builders, Excel converters, and data visualization utilities.`,
  },
  {
    slug: "performance",
    label: "Performance",
    icon: "⚡",
    description: "Speed testers, cache checkers, CDN analyzers, Core Web Vitals tools, and web optimization utilities.",
    seoTitle: `Performance Tools`,
    seoDescription: `Free online performance tools for ${SITE_NAME}. Speed testers, cache validators, CDN checkers, and web performance optimization utilities.`,
  },
  {
    slug: "devops",
    label: "DevOps",
    icon: "🛠️",
    description: "CI/CD tools, Docker utilities, Kubernetes guides, monitoring dashboards, and infrastructure management tools.",
    seoTitle: `DevOps Tools`,
    seoDescription: `Free online DevOps tools for ${SITE_NAME}. CI/CD utilities, Docker helpers, Kubernetes guides, monitoring dashboards, and infrastructure tools.`,
  },
  {
    slug: "cloud",
    label: "Cloud",
    icon: "☁️",
    description: "AWS tools, GCP guides, Azure utilities, cloud storage managers, and multi-cloud management resources.",
    seoTitle: `Cloud Tools`,
    seoDescription: `Free online cloud tools for ${SITE_NAME}. AWS utilities, GCP guides, Azure tools, cloud storage managers, and multi-cloud management resources.`,
  },
  {
    slug: "ecommerce",
    label: "E-commerce",
    icon: "🛒",
    description: "Product management tools, pricing calculators, shipping analyzers, inventory trackers, and e-commerce optimization utilities.",
    seoTitle: `E-commerce Tools`,
    seoDescription: `Free online e-commerce tools for ${SITE_NAME}. Product management utilities, pricing calculators, shipping analyzers, and store optimization tools.`,
  },
  {
    slug: "analytics",
    label: "Analytics",
    icon: "📈",
    description: "Tracking tools, data visualization, report generators, goal funnels, and business intelligence utilities.",
    seoTitle: `Analytics Tools`,
    seoDescription: `Free online analytics tools for ${SITE_NAME}. Tracking tools, data visualization, report generators, and business intelligence utilities.`,
  },
  {
    slug: "conversion",
    label: "Conversion Optimization",
    icon: "🎯",
    description: "A/B testing tools, landing page builders, funnel analyzers, heatmap generators, and CRO utilities.",
    seoTitle: `Conversion Optimization Tools`,
    seoDescription: `Free online conversion optimization tools for ${SITE_NAME}. A/B testing, landing page builders, funnel analyzers, and CRO utilities.`,
  },
  {
    slug: "email",
    label: "Email",
    icon: "📧",
    description: "Email marketing tools, automation builders, template editors, deliverability checkers, and newsletter utilities.",
    seoTitle: `Email Tools`,
    seoDescription: `Free online email tools for ${SITE_NAME}. Email marketing platforms, automation builders, template editors, and deliverability tools.`,
  },
  {
    slug: "social-media",
    label: "Social Media",
    icon: "📱",
    description: "Scheduling tools, analytics dashboards, content planners, hashtag generators, and social media management utilities.",
    seoTitle: `Social Media Tools`,
    seoDescription: `Free online social media tools for ${SITE_NAME}. Scheduling platforms, analytics dashboards, content planners, and hashtag generators.`,
  },
  {
    slug: "video",
    label: "Video",
    icon: "🎬",
    description: "Video editors, converters, screen recorders, streaming tools, and video optimization utilities.",
    seoTitle: `Video Tools`,
    seoDescription: `Free online video tools for ${SITE_NAME}. Video editors, format converters, screen recorders, streaming tools, and optimization utilities.`,
  },
  {
    slug: "audio",
    label: "Audio",
    icon: "🎧",
    description: "Audio editors, format converters, podcasting tools, voice recorders, and audio processing utilities.",
    seoTitle: `Audio Tools`,
    seoDescription: `Free online audio tools for ${SITE_NAME}. Audio editors, format converters, podcasting tools, and audio processing utilities.`,
  },
  {
    slug: "productivity-tools",
    label: "Productivity Apps",
    icon: "✅",
    description: "Task managers, calendar tools, time trackers, note-taking apps, and workflow automation utilities.",
    seoTitle: `Productivity Apps`,
    seoDescription: `Free online productivity apps for ${SITE_NAME}. Task managers, calendar tools, time trackers, note-taking apps, and workflow automation.`,
  },
  {
    slug: "finance-tools",
    label: "Finance Apps",
    icon: "💳",
    description: "Loan calculators, budget planners, investment trackers, tax estimators, and personal finance management tools.",
    seoTitle: `Finance Apps`,
    seoDescription: `Free online finance apps for ${SITE_NAME}. Loan calculators, budget planners, investment trackers, tax estimators, and personal finance tools.`,
  },
  {
    slug: "health",
    label: "Health & Fitness",
    icon: "🏥",
    description: "BMI calculators, fitness trackers, calorie counters, workout planners, and health monitoring tools.",
    seoTitle: `Health & Fitness Tools`,
    seoDescription: `Free online health and fitness tools for ${SITE_NAME}. BMI calculators, fitness trackers, workout planners, and health monitoring utilities.`,
  },
  {
    slug: "education",
    label: "Education",
    icon: "📚",
    description: "Learning tools, course builders, exam prep utilities, flashcard makers, and educational resource generators.",
    seoTitle: `Education Tools`,
    seoDescription: `Free online education tools for ${SITE_NAME}. Learning platforms, course builders, exam prep utilities, and educational resource generators.`,
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}


