export interface Tool {
  id: string;
  name: string;
  description: string;
  url: string;
  category: string;
  isFree: boolean;
  isFeatured: boolean;
}

export const tools: Tool[] = [
  {
    id: "domain-report",
    name: "Domain Report Card",
    description: "Get a complete A–F report card for any domain covering DNS health, SSL certificates, HTTP security headers, WHOIS registration, website status, and response time. Beautiful, shareable results.",
    url: "/domain-report",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  // ── Network & Internet ──────────────────────────────────────────
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    description: "Look up DNS records for any domain including A, AAAA, CNAME, MX, NS, TXT, SOA, SRV, and CAA records in one query.",
    url: "/dns-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "reverse-dns-lookup",
    name: "Reverse DNS Lookup",
    description: "Find the hostname associated with an IP address using reverse DNS (PTR record) lookup. Supports both IPv4 and IPv6 addresses.",
    url: "/reverse-dns-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dns-propagation-checker",
    name: "DNS Propagation Checker",
    description: "Check DNS propagation across multiple global DNS servers. See if your DNS changes have propagated to Google, Cloudflare, Quad9, OpenDNS, and more.",
    url: "/dns-propagation-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "whois-lookup",
    name: "WHOIS Lookup",
    description: "Look up domain registration information including registrar, creation date, expiration date, name servers, and contact details for any domain.",
    url: "/whois-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "http-headers-checker",
    name: "HTTP Headers Checker",
    description: "Check HTTP response headers for any URL. View status codes, cache policies, security headers, redirect chains, and response timing.",
    url: "/http-headers-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ssl-certificate-checker",
    name: "SSL Certificate Checker",
    description: "Check SSL/TLS certificate details for any domain. View certificate issuer, validity period, fingerprints, subject alternative names, and days until expiration.",
    url: "/ssl-certificate-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ping-test",
    name: "Ping Test",
    description: "Test network latency and packet loss to any host. Perform TCP ping with min, average, and max response time measurements.",
    url: "/ping-test",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "port-checker",
    name: "Port Checker",
    description: "Check if a network port is open on any host. Scan common ports or test a specific port. Includes service identification and response time.",
    url: "/port-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "website-status-checker",
    name: "Website Status Checker",
    description: "Check if a website is online and responding. Get HTTP status code, response time, content type, server information, and detailed status reports.",
    url: "/website-status-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "user-agent-parser",
    name: "User Agent Parser",
    description: "Parse any User-Agent string and identify the browser, engine, operating system, device model, and CPU architecture.",
    url: "/user-agent-parser",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate subnet details from an IP address and CIDR notation. Get network address, broadcast address, usable host range, subnet mask, and total hosts.",
    url: "/subnet-calculator",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },

  // ── Productivity ────────────────────────────────────────────────
  {
    id: "what-is-my-ip",
    name: "What Is My IP",
    description: "Find your public IPv4 and IPv6 address instantly. See location, ISP, ASN, timezone, and browser information.",
    url: "/what-is-my-ip",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ip-lookup",
    name: "IP Lookup",
    description: "Look up any IPv4 or IPv6 address. Get location, ISP, hostname, ASN, and interactive map.",
    url: "/ip-lookup",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with customizable length and character types. Create secure passwords for your online accounts instantly.",
    url: "/password-generator",
    category: "productivity",
    isFree: true,
    isFeatured: false,
  },

  // ── Text & Writing ──────────────────────────────────────────────
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate Lorem Ipsum placeholder text with customizable paragraph count, word count, and starting options. Perfect for mockups and design layouts.",
    url: "/lorem-ipsum-generator",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time in any text. Real-time text analysis with detailed statistics.",
    url: "/word-counter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two blocks of text and highlight the differences. Side-by-side diff view with added, removed, and unchanged lines.",
    url: "/text-diff-checker",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "list-randomizer",
    name: "List Randomizer",
    description: "Randomize the order of any list. Enter items separated by commas or newlines and shuffle them randomly. Perfect for giveaways, raffles, and random selection.",
    url: "/list-randomizer",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Remove duplicate lines from text. Keep only unique lines, sort results, and copy or download cleaned text with case-sensitive or case-insensitive matching.",
    url: "/remove-duplicate-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "sort-lines",
    name: "Sort Lines",
    description: "Sort lines of text alphabetically (A-Z or Z-A) with options for numeric sorting, case-insensitive sorting, duplicate removal, and custom ordering.",
    url: "/sort-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "reverse-text",
    name: "Reverse Text",
    description: "Reverse text at character, word, or line level. Flip entire strings, reverse word order, or invert line sequences instantly.",
    url: "/reverse-text",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "remove-empty-lines",
    name: "Remove Empty Lines",
    description: "Remove blank and empty lines from text. Strip whitespace-only lines and see a line count comparison before and after cleaning.",
    url: "/remove-empty-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Clean and normalize text with toggles for removing extra spaces, special characters, numbers, HTML tags, URLs, and smart quotes. See a live before-and-after preview.",
    url: "/text-cleaner",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "line-counter",
    name: "Line Counter",
    description: "Count lines in text with detailed real-time statistics including total lines, non-empty lines, empty lines, unique lines, and average line length.",
    url: "/line-counter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "find-and-replace",
    name: "Find and Replace",
    description: "Find and replace text in strings with options for case-sensitive matching, whole word matching, regex mode, and replace all. See the number of replacements made.",
    url: "/find-and-replace",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-splitter",
    name: "Text Splitter",
    description: "Split text by delimiter (newline, comma, space, or custom) and preview items. Output as comma-separated, newline-separated, or JSON array format.",
    url: "/text-splitter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-joiner",
    name: "Text Joiner",
    description: "Join multiple lines of text with a separator. Choose from comma, space, pipe, or custom separator. Add quotes around items with optional prefix and suffix.",
    url: "/text-joiner",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "excerpt-generator",
    name: "Excerpt Generator",
    description: "Generate text excerpts by word or character count. Add ellipsis, break at sentence boundaries, and see original vs excerpt length comparison.",
    url: "/excerpt-generator",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },

  // ── Image & Design ──────────────────────────────────────────────
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL. Download as PNG with customizable size. Create scannable QR codes for links, contacts, and more.",
    url: "/qr-code-generator",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images online. Upload an image and set custom dimensions. Maintain aspect ratio, preview before downloading. Supports JPEG, PNG, and WebP.",
    url: "/image-resizer",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS gradients with a visual editor. Generate linear and radial gradients with custom color stops. Copy CSS code instantly.",
    url: "/css-gradient-generator",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes online. Supports Code 128, EAN-13, and UPC-A formats. Download as PNG image for labels, packaging, and inventory.",
    url: "/barcode-generator",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },

  // ── Code & Development ──────────────────────────────────────────
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data with syntax highlighting and error detection. Beautify JSON responses from any API or configuration file.",
    url: "/json-formatter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings instantly. Supports Unicode text, URL-safe mode, and file attachment conversion.",
    url: "/base64-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URLs and query strings. Convert special characters to percent-encoded format and back.",
    url: "/url-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities. Escape special characters for safe HTML rendering and unescape encoded text.",
    url: "/html-entity-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens. View header, payload, signature, and expiration status without sending data to any server.",
    url: "/jwt-decoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate RFC 4122 UUID v4 identifiers instantly. Create bulk UUIDs for database keys, test fixtures, and correlation IDs.",
    url: "/uuid-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against sample text in real time. View all matches, capture groups, and positions with flag toggles.",
    url: "/regex-tester",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "md5-hash-generator",
    name: "MD5 Hash Generator",
    description: "Generate MD5 hash digests from text or files. Verify data integrity with the widely-used 128-bit cryptographic hash function.",
    url: "/md5-hash-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "sha-hash-generator",
    name: "SHA Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hash digests using the browser's native Web Crypto API.",
    url: "/sha-hash-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    description: "Minify and beautify HTML code. Remove whitespace, comments, and optional tags to reduce file size.",
    url: "/html-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "Minify and beautify CSS stylesheets. Compress CSS by removing whitespace, comments, and redundant rules.",
    url: "/css-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "js-minifier",
    name: "JS Minifier",
    description: "Minify and beautify JavaScript code. Reduce file size by stripping whitespace, comments, and shortening variable names.",
    url: "/js-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between camelCase, PascalCase, snake_case, kebab-case, title case, UPPER CASE, lower case, and more.",
    url: "/case-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal bases. Supports integer and fractional values.",
    url: "/number-base-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats with a live preview swatch. Get color harmonies and CSS-ready output.",
    url: "/color-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview Markdown in real time. Supports headings, lists, code blocks, tables, and more. Export rendered HTML.",
    url: "/markdown-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries. Supports SELECT, INSERT, UPDATE, DELETE statements. Make complex queries readable in seconds.",
    url: "/sql-formatter",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    description: "Write and preview HTML code in real time. Live rendering of HTML with CSS and JavaScript. Perfect for testing snippets before deployment.",
    url: "/html-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-to-slug",
    name: "Text to Slug Converter",
    description: "Convert any text to a URL-friendly slug. Remove special characters, replace spaces with hyphens, and generate SEO-friendly URLs.",
    url: "/text-to-slug",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description: "Parse any URL and view its components: protocol, hostname, path, query parameters, and fragment. Build and analyze URLs interactively.",
    url: "/url-parser",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "json-path-search",
    name: "JSON Path Search",
    description: "Search and filter JSON data using JSONPath expressions. Navigate complex JSON structures and extract specific values instantly.",
    url: "/json-path-search",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },

  // ── Data & Analytics ────────────────────────────────────────────
  {
    id: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON data to CSV format and back. Supports nested objects, arrays, and custom delimiters. Perfect for data migration and analysis.",
    url: "/json-to-csv",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON Converter",
    description: "Convert between YAML and JSON formats. Parse YAML files, edit in JSON, and convert back. Supports complex nested structures.",
    url: "/yaml-to-json",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "xml-to-json",
    name: "XML to JSON Converter",
    description: "Convert XML data to JSON format and back. Handle attributes, namespaces, and nested elements. Ideal for API integration and data transformation.",
    url: "/xml-to-json",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates. Supports milliseconds, seconds, and multiple timezone offsets.",
    url: "/timestamp-converter",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },

  // ── Image & Design Suite ──────────────────────────────────────
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images online. Reduce file size while maintaining quality. Free and private — all processing happens in your browser.",
    url: "/image-compressor",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPEG, PNG, WebP, GIF, BMP, and ICO formats online. Free and private — all processing happens in your browser.",
    url: "/image-converter",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "crop-image",
    name: "Crop Image",
    description: "Crop images online with preset aspect ratios or freeform. Upload, select crop area, preview, and download. Free and private — all processing happens in your browser.",
    url: "/crop-image",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "blur-image",
    name: "Blur Image",
    description: "Blur images online with adjustable radius. Apply Gaussian blur to sensitive content. Free and private — all processing happens in your browser.",
    url: "/blur-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "watermark-image",
    name: "Watermark Image",
    description: "Add text watermarks to images online. Customize text, position, opacity, font, and color. Free and private — all processing happens in your browser.",
    url: "/watermark-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove backgrounds from images using chroma key (green/blue screen). API-ready architecture for integrating AI-powered background removal services.",
    url: "/background-remover",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "image-metadata-viewer",
    name: "Image Metadata Viewer",
    description: "View EXIF and metadata from any image. Extract dimensions, file size, type, and basic camera EXIF data. Free and private — all processing happens in your browser.",
    url: "/image-metadata-viewer",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert any image to a Base64 data URI string. Copy to clipboard or download as a text file. Supports all image formats. Free and private.",
    url: "/image-to-base64",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image",
    description: "Decode a Base64 string back to an image. Paste a Base64 data URI or raw string, preview the image, and download. Free and private.",
    url: "/base64-to-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "image-grayscale",
    name: "Image Grayscale",
    description: "Convert images to grayscale or sepia online. Apply black and white effects with pixel-level Canvas processing. Free and private — all processing happens in your browser.",
    url: "/image-grayscale",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },

  // ── PDF Suite ───────────────────────────────────────────────────
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single PDF document. Upload up to 10 PDFs and merge them in any order.",
    url: "/merge-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into separate pages or page ranges. Extract individual pages and download them as separate files.",
    url: "/split-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size by removing metadata and optimizing content. Compress PDFs while preserving quality.",
    url: "/compress-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images. Select specific pages and download them as image files.",
    url: "/pdf-to-jpg",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG and PNG images to PDF documents. Upload multiple images and arrange them in any order.",
    url: "/jpg-to-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate PDF pages individually or all at once. Choose from 90, 180, or 270 degree rotation angles.",
    url: "/rotate-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "reorder-pdf",
    name: "Reorder PDF",
    description: "Rearrange pages in a PDF document. Move pages up or down to create the perfect page order.",
    url: "/reorder-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "extract-pdf-pages",
    name: "Extract PDF Pages",
    description: "Extract specific pages from a PDF document. Select individual pages and download them as a new PDF.",
    url: "/extract-pdf-pages",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files. Provide the document password and download the unlocked version.",
    url: "/unlock-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to PDF documents. Encrypt your PDF with a user password to restrict access.",
    url: "/protect-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },

  // ── SEO Suite ─────────────────────────────────────────────────────
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt files for your website. Allow or block search engine crawlers, set crawl delay, and specify sitemap URLs.",
    url: "/robots-txt-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemaps for your website. Add URLs with priorities, change frequencies, and last modified dates for better search engine indexing.",
    url: "/sitemap-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for SEO. Create title tags, meta descriptions, OG tags, Twitter cards, and viewport settings for better search visibility.",
    url: "/meta-tag-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "open-graph-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph meta tags for social sharing. Preview how your links look on Facebook, Twitter, LinkedIn, and other social platforms.",
    url: "/open-graph-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "schema-generator",
    name: "Schema Generator",
    description: "Generate JSON-LD schema markup for your website. Create structured data for articles, products, local businesses, FAQs, events, reviews, and more.",
    url: "/schema-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "hreflang-generator",
    name: "Hreflang Generator",
    description: "Generate hreflang tags for international SEO. Specify language and regional URLs so search engines serve the correct language version to users.",
    url: "/hreflang-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "canonical-generator",
    name: "Canonical URL Generator",
    description: "Generate canonical URL tags to prevent duplicate content issues. Set self-referencing canonicals and handle www vs non-www URL normalization.",
    url: "/canonical-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "redirect-checker",
    name: "Redirect Checker",
    description: "Check URL redirect chains and HTTP redirect status codes. Trace the full redirect path from initial request to final destination with status codes.",
    url: "/redirect-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "broken-link-checker",
    name: "Broken Link Checker",
    description: "Check multiple URLs for broken links. Test HTTP status codes, response times, and identify dead links on your website. Server-side implementation recommended for production.",
    url: "/broken-link-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "serp-preview",
    name: "SERP Preview Tool",
    description: "Preview how your webpage looks in Google search results. Optimize your title tags and meta descriptions with real-time character counting and mobile preview.",
    url: "/serp-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
];
