import type { FaqItem } from "./seo";

export const TOOL_FAQS: Record<string, FaqItem[]> = {
  "dns-lookup": [
    { question: "What is a DNS lookup?", answer: "A DNS lookup is a query that translates a domain name (like example.com) into an IP address (like 93.184.216.34). Every time you visit a website, your browser performs a DNS lookup to find the server's address. Our DNS Lookup tool makes this process visible, showing you every DNS record type for any domain." },
    { question: "What DNS record types can I check?", answer: "Our DNS Lookup tool supports A (IPv4), AAAA (IPv6), CNAME (aliases), MX (mail servers), NS (name servers), TXT (text/verification), SOA (zone authority), SRV (service locators), and CAA (CA authorization) records. Query all types at once or filter by specific record type." },
    { question: "How does DNS affect website speed?", answer: "DNS resolution adds 10-200ms to page load time depending on your resolver. A slow DNS lookup delays every resource on your page. Use our DNS Lookup to check resolution times, and consider switching to a fast public resolver like 1.1.1.1 or 8.8.8.8 for faster browsing." },
    { question: "What does NXDOMAIN mean?", answer: "NXDOMAIN means the domain name does not exist in DNS. This could mean the domain is not registered, the record was deleted, or there was a typo in the hostname. If you recently added a record and see NXDOMAIN, the change may not have propagated yet." },
    { question: "How do I check my DNS health?", answer: "Our DNS Lookup tool includes a built-in DNS health check that scores your domain on a 100-point scale based on A/AAAA records, SOA presence, NS delegation, MX configuration, and TXT/SPF records. A score below 50 indicates critical configuration issues." },
  ],
  "dns-propagation-checker": [
    { question: "What is DNS propagation?", answer: "DNS propagation is the time it takes for a DNS change to spread across all DNS resolvers worldwide. When you update a DNS record, the old value is cached by resolvers until their TTL expires. Our DNS Propagation Checker queries multiple global resolvers to show you exactly which ones have updated." },
    { question: "How long does DNS propagation take?", answer: "Propagation time depends on the TTL of the old record. With TTL of 300 seconds (5 minutes), propagation completes in about 5-10 minutes. With TTL of 86400 seconds (24 hours), it can take a full day or more. Lower your TTL 48 hours before planned changes for faster rollout." },
    { question: "Why do different locations show different DNS results?", answer: "Different DNS resolvers cache records independently based on their own TTL policies. Some resolvers enforce minimum cache times regardless of your TTL setting. Our Propagation Checker tests resolvers in the US, Europe, Asia, and Oceania to show you the global picture." },
    { question: "How do I use the DNS Propagation Checker?", answer: "Enter your domain name, select the record type (A, AAAA, MX, NS, TXT, or CNAME), and click Check. The tool queries Google, Cloudflare, Quad9, OpenDNS, and Mullvad resolvers simultaneously and shows each response. When all resolvers return the same value, propagation is complete." },
    { question: "Can I speed up DNS propagation?", answer: "You cannot force DNS propagation, but you can minimize its impact. Set up a maintenance page on both old and new IPs during migration. Use HTTP 307 redirects from the old server. The most effective strategy is to lower TTL to 60 seconds at least 48 hours before making changes." },
  ],
  "ssl-certificate-checker": [
    { question: "What does the SSL Certificate Checker do?", answer: "Our SSL Certificate Checker connects to any HTTPS server, retrieves the SSL/TLS certificate, and displays all critical details: issuer, validity period (valid from/to), days until expiration, subject alternative names (SANs), certificate chain, fingerprint, and the TLS protocol version in use." },
    { question: "How do I know if my SSL certificate is about to expire?", answer: "The SSL Certificate Checker shows the exact expiration date and the number of days remaining. A green status means more than 30 days remain. Yellow means 1-30 days (renew soon). Red means expired — renew immediately. We recommend renewing when 14 days remain to avoid any service disruption." },
    { question: "What is a certificate chain error?", answer: "A certificate chain error occurs when your server does not send the intermediate certificates needed to link your leaf certificate to a trusted root CA. Mobile clients and some API consumers may reject the connection. Our tool displays the full chain so you can see if any intermediate certificate is missing." },
    { question: "What TLS version should my server use?", answer: "TLS 1.2 and TLS 1.3 are the only secure TLS versions. TLS 1.0 and 1.1 are deprecated and should be disabled. TLS 1.3 offers faster handshakes (1-RTT vs 2-RTT) and better security. Our SSL Checker reports which TLS version your server negotiates." },
    { question: "What are Subject Alternative Names (SANs)?", answer: "SANs are domain names that a single SSL certificate can cover. A certificate for example.com can include www.example.com, mail.example.com, and other subdomains as SANs. Our tool lists all SANs on the certificate so you can verify all your domains are covered." },
  ],
  "http-headers-checker": [
    { question: "What are HTTP headers?", answer: "HTTP headers are metadata sent with every web request and response. They control security (CSP, HSTS, XFO), caching (Cache-Control), content negotiation (Content-Type), and cross-origin access (CORS). Our HTTP Headers Checker displays all response headers from any URL." },
    { question: "Which security headers are most important?", answer: "The six most important security headers are: Strict-Transport-Security (enforces HTTPS), Content-Security-Policy (prevents XSS), X-Frame-Options (prevents clickjacking), X-Content-Type-Options (prevents MIME sniffing), Referrer-Policy (controls referrer leakage), and Permissions-Policy (restricts API access). Our tool audits all six and assigns a security grade from A+ to F." },
    { question: "What is HSTS and why does it matter?", answer: "HTTP Strict-Transport-Security (HSTS) tells browsers to always connect via HTTPS, preventing downgrade attacks where an attacker intercepts the initial HTTP connection. Set max-age to at least 31536000 seconds (1 year) and include includeSubDomains once all subdomains support HTTPS." },
    { question: "How do I fix Content-Security-Policy violations?", answer: "CSP violations occur when your page loads resources from origins not listed in your policy. Check the browser console for violation reports. If you use CDNs or third-party widgets, ensure their origins are listed in the script-src and style-src directives. Use report-uri to collect violations without breaking functionality." },
    { question: "What is a good HTTP security grade?", answer: "An A+ grade means all six security headers are present and configured correctly with secure values. A B grade means some headers are present but may have weak configurations. A failing grade (D or F) means critical headers like HSTS and CSP are missing entirely. Use our tool to identify exactly which headers need attention." },
  ],
  "whois-lookup": [
    { question: "What information does WHOIS reveal about a domain?", answer: "WHOIS reveals the domain's registrar, registration and expiration dates, name servers, domain status codes, and the registrant's organization (if applicable). Personal data for individual registrants is typically redacted under GDPR. Our WHOIS Lookup tool queries registry databases and formats the results." },
    { question: "Why is WHOIS data often redacted?", answer: "Since the GDPR took effect in May 2018, ICANN requires registrars to redact personal information for natural persons. Fields that previously showed full name, address, phone, and email now show 'Redacted for Privacy' or similar. Organization and contact details are still visible for business-registered domains." },
    { question: "How do I find out when a domain expires?", answer: "Our WHOIS Lookup tool displays the expiration date prominently in the dashboard summary. It also shows the number of days until expiry and a visual expiry bar. If the domain is within 90 days of expiration, we recommend renewing immediately to avoid losing the domain." },
    { question: "What is domain age and why does it matter?", answer: "Domain age is how long ago a domain was registered. Older domains (5+ years) are generally trusted more by search engines and email systems. New domains (under 30 days) are often viewed with suspicion by spam filters. Our tool calculates domain age from the creation date in the WHOIS record." },
    { question: "What do domain status codes mean?", answer: "Domain status codes like clientTransferProhibited, redemptionPeriod, and pendingDelete indicate the domain's current state. clientTransferProhibited means the domain is locked against unauthorized transfers (good). redemptionPeriod means the domain expired and is in a 30-day grace period before public release." },
  ],
  "ping-test": [
    { question: "What is a ping test?", answer: "A ping test measures the round-trip time for data to travel from your device to a destination server and back. It reveals network latency, packet loss, and connection stability. Our Ping Test uses TCP connections rather than ICMP, making results more representative of real application traffic like web browsing and API calls." },
    { question: "What is a good ping time?", answer: "Under 20ms is excellent (ideal for competitive gaming). 20-50ms is very good (smooth video calls). 50-100ms is good (normal web browsing). 100-200ms is fair (noticeable lag for real-time apps). Above 200ms is poor (asynchronous tasks only, like email). Our tool assigns a quality score and provides specific recommendations." },
    { question: "What is jitter and why does it matter?", answer: "Jitter is the variation in ping times between consecutive tests. Low jitter (under 10ms) means a stable connection. Jitter over 30ms causes noticeable quality issues in VoIP calls and video conferencing. Our Ping Test reports jitter alongside average latency and provides optimization advice." },
    { question: "What causes packet loss?", answer: "Packet loss can result from Wi-Fi interference, faulty Ethernet cables, ISP congestion, overloaded routers, or failing network hardware. Even 1% packet loss degrades real-time applications. Our tool tracks loss across multiple attempts and helps isolate whether the cause is local or remote." },
    { question: "How is TCP ping different from ICMP ping?", answer: "Traditional ping uses ICMP echo requests. Our TCP ping connects to a service port (like HTTP on port 80), which better represents actual application traffic. Many networks prioritize or deprioritize ICMP differently from TCP, so TCP ping results are more actionable for diagnosing real-world performance." },
  ],
  "port-checker": [
    { question: "What is a port checker?", answer: "A port checker scans a host to see which network ports are open, closed, or filtered. It reveals which services are accessible from the internet. Our Port Checker tests common ports and lets you check specific ports on any hostname or IP address." },
    { question: "What's the difference between open, closed, and filtered?", answer: "Open means a service is accepting connections on that port. Closed means the port is reachable but no service is listening. Filtered means no response was received — a firewall is silently dropping packets, so we cannot tell if a service is there or not." },
    { question: "Why does my port show as filtered when it should be open?", answer: "A filtered port typically indicates a firewall, NAT, or security group blocking the connection. Check both your cloud security group and OS-level firewall. If you're behind Carrier-Grade NAT (CGNAT), you cannot receive inbound connections at all — request a public IP from your ISP." },
    { question: "Which ports are most commonly attacked?", answer: "Ports 22 (SSH), 23 (Telnet), 25 (SMTP), 3389 (RDP), 445 (SMB), 3306 (MySQL), 5432 (PostgreSQL), 6379 (Redis), and 27017 (MongoDB) are heavily targeted. Our tool highlights risky open ports in the dashboard summary and calculates an attack surface score." },
    { question: "How often should I scan my ports?", answer: "Run a port scan weekly on all public IPs. New services, temporary configurations, and deployment scripts can unintentionally open ports. Any unauthorized open port should trigger an investigation. Our Port Checker includes an attack surface score to help you track changes over time." },
  ],
  "ip-lookup": [
    { question: "What is an IP lookup?", answer: "An IP lookup retrieves geographic and network information about any IP address. Our IP Lookup tool shows the country, region, city, ISP, ASN, hostname, timezone, coordinates, and more. It works for both IPv4 and IPv6 addresses." },
    { question: "How accurate is IP geolocation?", answer: "IP geolocation is typically accurate to the city level for residential IPs (85-95% in developed countries). Mobile IPs are less accurate (50-70%) because traffic routes through carrier gateways far from the user. Datacenter IPs show the facility location, not the user. Geolocation cannot provide street-level accuracy." },
    { question: "What is an ASN?", answer: "An Autonomous System Number (ASN) identifies the network operator that owns an IP block. Each ISP and cloud provider has one or more ASNs. The ASN reveals who operates the network, which is useful for security investigations and understanding internet routing." },
    { question: "Can IP lookup detect VPNs?", answer: "Our IP Lookup tool identifies the ISP and organization associated with an IP. Datacenter and hosting provider IPs (AWS, DigitalOcean, Hetzner) are strong indicators of VPN or proxy use. Residential ISP IPs suggest a regular user connection." },
    { question: "What does the privacy score mean?", answer: "The privacy score indicates how much information your IP reveals. A higher score (green) means less data is exposed — your IP is from a residential ISP with limited public information. A lower score means more data is publicly available about the IP, such as detailed hosting provider information." },
  ],
  "what-is-my-ip": [
    { question: "What is my IP address?", answer: "Your public IP address is the unique identifier the internet sees when you connect. It is assigned by your ISP and can be either IPv4 (like 192.0.2.1) or IPv6 (like 2001:db8::1). Our What Is My IP tool automatically detects and displays both addresses, your location, ISP, and browser information." },
    { question: "Does my IP address change?", answer: "Most residential ISPs assign dynamic IPs that change periodically — when your router reboots or the DHCP lease expires (typically every 24-48 hours). Business accounts often get static IPs. If your IP changes frequently, consider a static IP from your ISP or a Dynamic DNS (DDNS) service." },
    { question: "How do I check if my VPN is working?", answer: "Connect to your VPN, then visit our What Is My IP tool. If the displayed IP matches your VPN provider's IP range (not your ISP's), the VPN is working. Also check that your IPv6 address matches — if IPv4 shows the VPN but IPv6 shows your ISP, you have an IPv6 leak." },
    { question: "What is a WebRTC leak?", answer: "WebRTC (Web Real-Time Communication) can bypass your VPN and reveal your real IP address through STUN requests, even without your permission. Our What Is My IP tool helps detect WebRTC leaks. If you see a different IP from your VPN IP, install a WebRTC blocking extension." },
    { question: "What information does my IP reveal about me?", answer: "Your public IP reveals your approximate city-level location, ISP name, and connection type (residential/business/mobile). It does NOT reveal your exact address, name, or identity. However, websites can combine your IP with other data (cookies, login info, browser fingerprinting) to build a more detailed profile." },
  ],
};
