export interface Tool {
  id: string;
  name: string;
  description: string;
  url: string;
  category: string;
  isFree: boolean;
  isFeatured: boolean;
}

export const tools: Tool[] = [
  {
    id: "domain-report",
    name: "Domain Report Card",
    description: "Get a complete A–F report card for any domain covering DNS health, SSL certificates, HTTP security headers, WHOIS registration, website status, and response time. Beautiful, shareable results.",
    url: "/domain-report",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  // ── Network & Internet ──────────────────────────────────────────
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    description: "Look up DNS records for any domain including A, AAAA, CNAME, MX, NS, TXT, SOA, SRV, and CAA records in one query.",
    url: "/dns-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "reverse-dns-lookup",
    name: "Reverse DNS Lookup",
    description: "Find the hostname associated with an IP address using reverse DNS (PTR record) lookup. Supports both IPv4 and IPv6 addresses.",
    url: "/reverse-dns-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dns-propagation-checker",
    name: "DNS Propagation Checker",
    description: "Check DNS propagation across multiple global DNS servers. See if your DNS changes have propagated to Google, Cloudflare, Quad9, OpenDNS, and more.",
    url: "/dns-propagation-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "whois-lookup",
    name: "WHOIS Lookup",
    description: "Look up domain registration information including registrar, creation date, expiration date, name servers, and contact details for any domain.",
    url: "/whois-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "http-headers-checker",
    name: "HTTP Headers Checker",
    description: "Check HTTP response headers for any URL. View status codes, cache policies, security headers, redirect chains, and response timing.",
    url: "/http-headers-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ssl-certificate-checker",
    name: "SSL Certificate Checker",
    description: "Check SSL/TLS certificate details for any domain. View certificate issuer, validity period, fingerprints, subject alternative names, and days until expiration.",
    url: "/ssl-certificate-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ping-test",
    name: "Ping Test",
    description: "Test network latency and packet loss to any host. Perform TCP ping with min, average, and max response time measurements.",
    url: "/ping-test",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "port-checker",
    name: "Port Checker",
    description: "Check if a network port is open on any host. Scan common ports or test a specific port. Includes service identification and response time.",
    url: "/port-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "website-status-checker",
    name: "Website Status Checker",
    description: "Check if a website is online and responding. Get HTTP status code, response time, content type, server information, and detailed status reports.",
    url: "/website-status-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "user-agent-parser",
    name: "User Agent Parser",
    description: "Parse any User-Agent string and identify the browser, engine, operating system, device model, and CPU architecture.",
    url: "/user-agent-parser",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Calculate subnet details from an IP address and CIDR notation. Get network address, broadcast address, usable host range, subnet mask, and total hosts.",
    url: "/subnet-calculator",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },

  // ── Productivity ────────────────────────────────────────────────
  {
    id: "what-is-my-ip",
    name: "What Is My IP",
    description: "Find your public IPv4 and IPv6 address instantly. See location, ISP, ASN, timezone, and browser information.",
    url: "/what-is-my-ip",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "ip-lookup",
    name: "IP Lookup",
    description: "Look up any IPv4 or IPv6 address. Get location, ISP, hostname, ASN, and interactive map.",
    url: "/ip-lookup",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with customizable length and character types. Create secure passwords for your online accounts instantly.",
    url: "/password-generator",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },

  // ── Text & Writing ──────────────────────────────────────────────
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate Lorem Ipsum placeholder text with customizable paragraph count, word count, and starting options. Perfect for mockups and design layouts.",
    url: "/lorem-ipsum-generator",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, paragraphs, and reading time in any text. Real-time text analysis with detailed statistics.",
    url: "/word-counter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-diff-checker",
    name: "Text Diff Checker",
    description: "Compare two blocks of text and highlight the differences. Side-by-side diff view with added, removed, and unchanged lines.",
    url: "/text-diff-checker",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "list-randomizer",
    name: "List Randomizer",
    description: "Randomize the order of any list. Enter items separated by commas or newlines and shuffle them randomly. Perfect for giveaways, raffles, and random selection.",
    url: "/list-randomizer",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Remove duplicate lines from text. Keep only unique lines, sort results, and copy or download cleaned text with case-sensitive or case-insensitive matching.",
    url: "/remove-duplicate-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "sort-lines",
    name: "Sort Lines",
    description: "Sort lines of text alphabetically (A-Z or Z-A) with options for numeric sorting, case-insensitive sorting, duplicate removal, and custom ordering.",
    url: "/sort-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "reverse-text",
    name: "Reverse Text",
    description: "Reverse text at character, word, or line level. Flip entire strings, reverse word order, or invert line sequences instantly.",
    url: "/reverse-text",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "remove-empty-lines",
    name: "Remove Empty Lines",
    description: "Remove blank and empty lines from text. Strip whitespace-only lines and see a line count comparison before and after cleaning.",
    url: "/remove-empty-lines",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Clean and normalize text with toggles for removing extra spaces, special characters, numbers, HTML tags, URLs, and smart quotes. See a live before-and-after preview.",
    url: "/text-cleaner",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "line-counter",
    name: "Line Counter",
    description: "Count lines in text with detailed real-time statistics including total lines, non-empty lines, empty lines, unique lines, and average line length.",
    url: "/line-counter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "find-and-replace",
    name: "Find and Replace",
    description: "Find and replace text in strings with options for case-sensitive matching, whole word matching, regex mode, and replace all. See the number of replacements made.",
    url: "/find-and-replace",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-splitter",
    name: "Text Splitter",
    description: "Split text by delimiter (newline, comma, space, or custom) and preview items. Output as comma-separated, newline-separated, or JSON array format.",
    url: "/text-splitter",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-joiner",
    name: "Text Joiner",
    description: "Join multiple lines of text with a separator. Choose from comma, space, pipe, or custom separator. Add quotes around items with optional prefix and suffix.",
    url: "/text-joiner",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "excerpt-generator",
    name: "Excerpt Generator",
    description: "Generate text excerpts by word or character count. Add ellipsis, break at sentence boundaries, and see original vs excerpt length comparison.",
    url: "/excerpt-generator",
    category: "text-writing",
    isFree: true,
    isFeatured: false,
  },

  // ── Image & Design ──────────────────────────────────────────────
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL. Download as PNG with customizable size. Create scannable QR codes for links, contacts, and more.",
    url: "/qr-code-generator",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images online. Upload an image and set custom dimensions. Maintain aspect ratio, preview before downloading. Supports JPEG, PNG, and WebP.",
    url: "/image-resizer",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "css-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS gradients with a visual editor. Generate linear and radial gradients with custom color stops. Copy CSS code instantly.",
    url: "/css-gradient-generator",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes online. Supports Code 128, EAN-13, and UPC-A formats. Download as PNG image for labels, packaging, and inventory.",
    url: "/barcode-generator",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },

  // ── Code & Development ──────────────────────────────────────────
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data with syntax highlighting and error detection. Beautify JSON responses from any API or configuration file.",
    url: "/json-formatter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode and decode Base64 strings instantly. Supports Unicode text, URL-safe mode, and file attachment conversion.",
    url: "/base64-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URLs and query strings. Convert special characters to percent-encoded format and back.",
    url: "/url-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities. Escape special characters for safe HTML rendering and unescape encoded text.",
    url: "/html-entity-encoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens. View header, payload, signature, and expiration status without sending data to any server.",
    url: "/jwt-decoder",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate RFC 4122 UUID v4 identifiers instantly. Create bulk UUIDs for database keys, test fixtures, and correlation IDs.",
    url: "/uuid-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions against sample text in real time. View all matches, capture groups, and positions with flag toggles.",
    url: "/regex-tester",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "md5-hash-generator",
    name: "MD5 Hash Generator",
    description: "Generate MD5 hash digests from text or files. Verify data integrity with the widely-used 128-bit cryptographic hash function.",
    url: "/md5-hash-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "sha-hash-generator",
    name: "SHA Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hash digests using the browser's native Web Crypto API.",
    url: "/sha-hash-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "html-minifier",
    name: "HTML Minifier",
    description: "Minify and beautify HTML code. Remove whitespace, comments, and optional tags to reduce file size.",
    url: "/html-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "Minify and beautify CSS stylesheets. Compress CSS by removing whitespace, comments, and redundant rules.",
    url: "/css-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "js-minifier",
    name: "JS Minifier",
    description: "Minify and beautify JavaScript code. Reduce file size by stripping whitespace, comments, and shortening variable names.",
    url: "/js-minifier",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between camelCase, PascalCase, snake_case, kebab-case, title case, UPPER CASE, lower case, and more.",
    url: "/case-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal bases. Supports integer and fractional values.",
    url: "/number-base-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats with a live preview swatch. Get color harmonies and CSS-ready output.",
    url: "/color-converter",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview Markdown in real time. Supports headings, lists, code blocks, tables, and more. Export rendered HTML.",
    url: "/markdown-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries. Supports SELECT, INSERT, UPDATE, DELETE statements. Make complex queries readable in seconds.",
    url: "/sql-formatter",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    description: "Write and preview HTML code in real time. Live rendering of HTML with CSS and JavaScript. Perfect for testing snippets before deployment.",
    url: "/html-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "text-to-slug",
    name: "Text to Slug Converter",
    description: "Convert any text to a URL-friendly slug. Remove special characters, replace spaces with hyphens, and generate SEO-friendly URLs.",
    url: "/text-to-slug",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description: "Parse any URL and view its components: protocol, hostname, path, query parameters, and fragment. Build and analyze URLs interactively.",
    url: "/url-parser",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "json-path-search",
    name: "JSON Path Search",
    description: "Search and filter JSON data using JSONPath expressions. Navigate complex JSON structures and extract specific values instantly.",
    url: "/json-path-search",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },

  // ── Data & Analytics ────────────────────────────────────────────
  {
    id: "json-to-csv",
    name: "JSON to CSV Converter",
    description: "Convert JSON data to CSV format and back. Supports nested objects, arrays, and custom delimiters. Perfect for data migration and analysis.",
    url: "/json-to-csv",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON Converter",
    description: "Convert between YAML and JSON formats. Parse YAML files, edit in JSON, and convert back. Supports complex nested structures.",
    url: "/yaml-to-json",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "xml-to-json",
    name: "XML to JSON Converter",
    description: "Convert XML data to JSON format and back. Handle attributes, namespaces, and nested elements. Ideal for API integration and data transformation.",
    url: "/xml-to-json",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates. Supports milliseconds, seconds, and multiple timezone offsets.",
    url: "/timestamp-converter",
    category: "data-analytics",
    isFree: true,
    isFeatured: false,
  },

  // ── Image & Design Suite ──────────────────────────────────────
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPEG, PNG, and WebP images online. Reduce file size while maintaining quality. Free and private — all processing happens in your browser.",
    url: "/image-compressor",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPEG, PNG, WebP, GIF, BMP, and ICO formats online. Free and private — all processing happens in your browser.",
    url: "/image-converter",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "crop-image",
    name: "Crop Image",
    description: "Crop images online with preset aspect ratios or freeform. Upload, select crop area, preview, and download. Free and private — all processing happens in your browser.",
    url: "/crop-image",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "blur-image",
    name: "Blur Image",
    description: "Blur images online with adjustable radius. Apply Gaussian blur to sensitive content. Free and private — all processing happens in your browser.",
    url: "/blur-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "watermark-image",
    name: "Watermark Image",
    description: "Add text watermarks to images online. Customize text, position, opacity, font, and color. Free and private — all processing happens in your browser.",
    url: "/watermark-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove backgrounds from images using chroma key (green/blue screen). API-ready architecture for integrating AI-powered background removal services.",
    url: "/background-remover",
    category: "image-design",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "image-metadata-viewer",
    name: "Image Metadata Viewer",
    description: "View EXIF and metadata from any image. Extract dimensions, file size, type, and basic camera EXIF data. Free and private — all processing happens in your browser.",
    url: "/image-metadata-viewer",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Convert any image to a Base64 data URI string. Copy to clipboard or download as a text file. Supports all image formats. Free and private.",
    url: "/image-to-base64",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image",
    description: "Decode a Base64 string back to an image. Paste a Base64 data URI or raw string, preview the image, and download. Free and private.",
    url: "/base64-to-image",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "image-grayscale",
    name: "Image Grayscale",
    description: "Convert images to grayscale or sepia online. Apply black and white effects with pixel-level Canvas processing. Free and private — all processing happens in your browser.",
    url: "/image-grayscale",
    category: "image-design",
    isFree: true,
    isFeatured: false,
  },

  // ── PDF Suite ───────────────────────────────────────────────────
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single PDF document. Upload up to 10 PDFs and merge them in any order.",
    url: "/merge-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into separate pages or page ranges. Extract individual pages and download them as separate files.",
    url: "/split-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size by removing metadata and optimizing content. Compress PDFs while preserving quality.",
    url: "/compress-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages to high-quality JPG images. Select specific pages and download them as image files.",
    url: "/pdf-to-jpg",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG and PNG images to PDF documents. Upload multiple images and arrange them in any order.",
    url: "/jpg-to-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate PDF pages individually or all at once. Choose from 90, 180, or 270 degree rotation angles.",
    url: "/rotate-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "reorder-pdf",
    name: "Reorder PDF",
    description: "Rearrange pages in a PDF document. Move pages up or down to create the perfect page order.",
    url: "/reorder-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "extract-pdf-pages",
    name: "Extract PDF Pages",
    description: "Extract specific pages from a PDF document. Select individual pages and download them as a new PDF.",
    url: "/extract-pdf-pages",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from PDF files. Provide the document password and download the unlocked version.",
    url: "/unlock-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to PDF documents. Encrypt your PDF with a user password to restrict access.",
    url: "/protect-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents (.doc). Extract text content from PDFs and download as Word-compatible format. Free and private.",
    url: "/pdf-to-word",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Microsoft Word documents (.docx) to PDF format instantly in your browser.",
    url: "/word-to-pdf",
    category: "productivity",
    isFree: true,
    isFeatured: true,
  },

  // ── SEO Suite ─────────────────────────────────────────────────────
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt files for your website. Allow or block search engine crawlers, set crawl delay, and specify sitemap URLs.",
    url: "/robots-txt-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemaps for your website. Add URLs with priorities, change frequencies, and last modified dates for better search engine indexing.",
    url: "/sitemap-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for SEO. Create title tags, meta descriptions, OG tags, Twitter cards, and viewport settings for better search visibility.",
    url: "/meta-tag-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "open-graph-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph meta tags for social sharing. Preview how your links look on Facebook, Twitter, LinkedIn, and other social platforms.",
    url: "/open-graph-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "schema-generator",
    name: "Schema Generator",
    description: "Generate JSON-LD schema markup for your website. Create structured data for articles, products, local businesses, FAQs, events, reviews, and more.",
    url: "/schema-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "hreflang-generator",
    name: "Hreflang Generator",
    description: "Generate hreflang tags for international SEO. Specify language and regional URLs so search engines serve the correct language version to users.",
    url: "/hreflang-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "canonical-generator",
    name: "Canonical URL Generator",
    description: "Generate canonical URL tags to prevent duplicate content issues. Set self-referencing canonicals and handle www vs non-www URL normalization.",
    url: "/canonical-generator",
    category: "code-dev",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "redirect-checker",
    name: "Redirect Checker",
    description: "Check URL redirect chains and HTTP redirect status codes. Trace the full redirect path from initial request to final destination with status codes.",
    url: "/redirect-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "broken-link-checker",
    name: "Broken Link Checker",
    description: "Check multiple URLs for broken links. Test HTTP status codes, response times, and identify dead links on your website. Server-side implementation recommended for production.",
    url: "/broken-link-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "serp-preview",
    name: "SERP Preview Tool",
    description: "Preview how your webpage looks in Google search results. Optimize your title tags and meta descriptions with real-time character counting and mobile preview.",
    url: "/serp-preview",
    category: "code-dev",
    isFree: true,
    isFeatured: true,
  },
  // ── Email Authentication ─────────────────────────────────────────
  {
    id: "spf-lookup",
    name: "SPF Lookup",
    description: "Check SPF (Sender Policy Framework) records for any domain. Verify which mail servers are authorized to send email on behalf of a domain.",
    url: "/spf-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dkim-lookup",
    name: "DKIM Lookup",
    description: "Look up DKIM (DomainKeys Identified Mail) records for any domain. Verify email signing configuration and check cryptographic signatures.",
    url: "/dkim-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dmarc-lookup",
    name: "DMARC Lookup",
    description: "Check DMARC (Domain-based Message Authentication, Reporting & Conformance) records. Verify email authentication policy and reporting configuration.",
    url: "/dmarc-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "mx-lookup",
    name: "MX Lookup",
    description: "Check MX (Mail Exchange) records for any domain. Find which mail servers handle email delivery and verify their priority order.",
    url: "/mx-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "bimi-lookup",
    name: "BIMI Lookup",
    description: "Check BIMI (Brand Indicators for Message Identification) records. Verify brand logo association and VMC (Verified Mark Certificate) status for email display.",
    url: "/bimi-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "spf-generator",
    name: "SPF Record Generator",
    description: "Generate SPF (Sender Policy Framework) records for your domain. Create allowlists for mail servers and configure email authentication policies.",
    url: "/spf-generator",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dmarc-generator",
    name: "DMARC Record Generator",
    description: "Generate DMARC (Domain-based Message Authentication, Reporting & Conformance) records. Configure email authentication policies, reporting, and enforcement.",
    url: "/dmarc-generator",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dkim-validator",
    name: "DKIM Record Validator",
    description: "Validate DKIM (DomainKeys Identified Mail) DNS records. Verify proper formatting, key type, and cryptographic correctness of email signing keys.",
    url: "/dkim-validator",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },
  // ── DNS Flagship Tools ─────────────────────────────────────────────
  {
    id: "dnssec-checker",
    name: "DNSSEC Checker",
    description: "Check if a domain has DNSSEC enabled. Verify DNSKEY, RRSIG, and DS records to confirm cryptographic signing and protection against DNS spoofing.",
    url: "/dnssec-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "caa-lookup",
    name: "CAA Lookup",
    description: "Look up CAA (Certificate Authority Authorization) records. Verify which Certificate Authorities are authorized to issue SSL/TLS certificates for your domain.",
    url: "/caa-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "nameserver-analyzer",
    name: "Nameserver Analyzer",
    description: "Analyze nameserver configuration for any domain. Verify NS records, check nameserver reachability, identify configuration issues, and ensure DNS redundancy.",
    url: "/nameserver-analyzer",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "dns-zone-validator",
    name: "DNS Zone Validator",
    description: "Validate DNS zone configuration. Scan all essential record types, detect missing records, misconfigurations, and potential issues affecting reliability.",
    url: "/dns-zone-validator",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "email-deliverability-checker",
    name: "Email Deliverability Checker",
    description: "Audit email deliverability health. Check SPF, DKIM, DMARC, MX, and PTR records with a deliverability score and actionable recommendations.",
    url: "/email-deliverability-checker",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  // ── Sprint 25 — Enterprise Network Tools ───────────────────────────
  {
    id: "blacklist-check",
    name: "Blacklist Check",
    description: "Check if an IP address is listed on 10+ DNS blacklists including Spamhaus, SpamCop, Barracuda, and SORBS. Free DNSBL reputation lookup.",
    url: "/blacklist-check",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "mta-sts-lookup",
    name: "MTA-STS Lookup",
    description: "Check MTA-STS (Mail Transfer Agent Strict Transport Security) records. Verify TLS enforcement policy for incoming email per RFC 8461.",
    url: "/mta-sts-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "asn-lookup",
    name: "ASN Lookup",
    description: "Look up ASN (Autonomous System Number) information for any IP address. Find network owner, organization, and registration details via RDAP.",
    url: "/asn-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },
  {
    id: "srv-lookup",
    name: "SRV Lookup",
    description: "Look up SRV (Service) records for any domain. Find service locations for SIP, LDAP, XMPP, Kerberos, and more per RFC 2782.",
    url: "/srv-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: false,
  },
  {
    id: "tlsrpt-lookup",
    name: "TLSRPT Lookup",
    description: "Look up TLSRPT (TLS Reporting) records. Verify TLS reporting configuration for SMTP and monitor TLS connection failures per RFC 8460.",
    url: "/tlsrpt-lookup",
    category: "network-internet",
    isFree: true,
    isFeatured: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // Sprint 25 — 100+ New Tools
  // ═══════════════════════════════════════════════════════════════

  // ── Finance ─────────────────────────────────────────────────
  { id: "mortgage-calculator", name: "Mortgage Calculator", description: "Calculate monthly mortgage payments with principal, interest, taxes, and insurance. Compare 15-year vs 30-year loan terms with amortization schedules.", url: "/mortgage-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "loan-calculator", name: "Loan Calculator", description: "Calculate monthly loan payments for personal, auto, and student loans. View amortization tables and total interest paid over the loan term.", url: "/loan-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "compound-interest-calculator", name: "Compound Interest Calculator", description: "Calculate compound interest growth over time with regular contributions. Visualize investment growth with charts and year-by-year breakdowns.", url: "/compound-interest-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "tip-calculator", name: "Tip Calculator", description: "Calculate tip amounts for restaurant bills. Split bills among multiple people with customizable tip percentages and round-up options.", url: "/tip-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "salary-calculator", name: "Salary Calculator", description: "Convert between hourly, weekly, monthly, and annual salary. Calculate take-home pay after taxes and deductions with customizable tax rates.", url: "/salary-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "budget-calculator", name: "Budget Calculator", description: "Create a personal budget by categorizing income and expenses. Track spending by category and calculate monthly savings automatically.", url: "/budget-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "vat-calculator", name: "VAT Calculator", description: "Calculate VAT amounts for prices inclusive and exclusive of tax. Supports multiple VAT rates and currency formats for international use.", url: "/vat-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "currency-converter", name: "Currency Converter", description: "Convert between 160+ world currencies using real exchange rates. Historical rate lookup and inverse conversion for international transactions.", url: "/currency-converter", category: "finance", isFree: true, isFeatured: false },
  { id: "percentage-calculator", name: "Percentage Calculator", description: "Calculate percentages, percentage changes, and percentage differences. Find what percent one number is of another and apply percentage increases or decreases.", url: "/percentage-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "retirement-calculator", name: "Retirement Calculator", description: "Estimate how much you need to save for retirement. Factor in current savings, monthly contributions, expected returns, and inflation for a comprehensive projection.", url: "/retirement-calculator", category: "finance", isFree: true, isFeatured: false },
  { id: "crypto-converter", name: "Crypto Converter", description: "Convert between 50+ cryptocurrencies and fiat currencies. Real-time prices for Bitcoin, Ethereum, and major altcoins with historical trends.", url: "/crypto-converter", category: "finance", isFree: true, isFeatured: false },

  // ── Calculators ─────────────────────────────────────────────
  { id: "bmi-calculator", name: "BMI Calculator", description: "Calculate your Body Mass Index (BMI) from height and weight. View BMI category and healthy weight range with WHO classification standards.", url: "/bmi-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "calorie-calculator", name: "Calorie Calculator", description: "Calculate daily calorie needs based on age, gender, weight, height, and activity level. Get BMR, TDEE, and calorie targets for weight goals.", url: "/calorie-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "age-calculator", name: "Age Calculator", description: "Calculate exact age in years, months, days, hours, minutes, and seconds. Find days until next birthday, age on any date, and chronological age.", url: "/age-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "date-calculator", name: "Date Calculator", description: "Add or subtract days, weeks, months, and years from any date. Calculate duration between two dates in days, weeks, months, and years.", url: "/date-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "time-calculator", name: "Time Calculator", description: "Add, subtract, multiply, and divide time values. Calculate time durations and convert between hours, minutes, seconds, and decimal formats.", url: "/time-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "unit-converter", name: "Unit Converter", description: "Convert between 500+ units across 20+ categories: length, mass, volume, temperature, area, speed, pressure, energy, power, and more.", url: "/unit-converter", category: "calculators", isFree: true, isFeatured: false },
  { id: "scientific-calculator", name: "Scientific Calculator", description: "Perform scientific calculations with trigonometric, logarithmic, exponential, and statistical functions. Supports degrees, radians, and gradians.", url: "/scientific-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "random-number-generator", name: "Random Number Generator", description: "Generate random numbers within any range. Supports integers, decimals, unique numbers, and multiple number generation modes with true randomness.", url: "/random-number-generator", category: "calculators", isFree: true, isFeatured: false },
  { id: "distance-calculator", name: "Distance Calculator", description: "Calculate distance between two points using coordinates (latitude/longitude). Get results in kilometers, miles, and nautical miles with great-circle formula.", url: "/distance-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "fuel-calculator", name: "Fuel Cost Calculator", description: "Calculate fuel cost for a trip based on distance, fuel efficiency, and fuel price. Compare fuel costs between different vehicles and journey types.", url: "/fuel-calculator", category: "calculators", isFree: true, isFeatured: false },
  { id: "gpa-calculator", name: "GPA Calculator", description: "Calculate grade point average for high school, college, and university courses. Supports weighted, unweighted, and cumulative GPA with letter grade and percentage inputs.", url: "/gpa-calculator", category: "calculators", isFree: true, isFeatured: false },

  // ── Security ────────────────────────────────────────────────
  { id: "password-strength-checker", name: "Password Strength Checker", description: "Check password strength with real-time analysis. Evaluate length, complexity, entropy, and time-to-crack. Get actionable suggestions for stronger passwords.", url: "/password-strength-checker", category: "security", isFree: true, isFeatured: false },
  { id: "data-breach-checker", name: "Data Breach Checker", description: "Check if your email or username appears in known data breaches. Search against major breach databases for compromised credentials.", url: "/data-breach-checker", category: "security", isFree: true, isFeatured: false },
  { id: "csrf-token-generator", name: "CSRF Token Generator", description: "Generate cryptographically secure CSRF tokens for web forms. Create random tokens with configurable length and encoding for cross-site request forgery protection.", url: "/csrf-token-generator", category: "security", isFree: true, isFeatured: false },
  { id: "ssl-test", name: "SSL Test", description: "Comprehensive SSL/TLS server test. Check protocol support (TLS 1.0-1.3), cipher suites, certificate chain, HSTS, and security vulnerabilities.", url: "/ssl-test", category: "security", isFree: true, isFeatured: false },
  { id: "cors-checker", name: "CORS Checker", description: "Test CORS (Cross-Origin Resource Sharing) configuration for any URL. Verify allowed origins, methods, headers, and preflight response handling.", url: "/cors-checker", category: "security", isFree: true, isFeatured: false },
  { id: "content-security-policy", name: "CSP Generator", description: "Generate Content Security Policy headers to prevent XSS attacks. Configure directives for scripts, styles, images, fonts, and frames with a visual builder.", url: "/content-security-policy", category: "security", isFree: true, isFeatured: false },
  { id: "hash-comparison", name: "Hash Comparison Tool", description: "Compare two hashes or compute and compare file hashes. Verify data integrity with SHA-256, MD5, or custom hash algorithm matching.", url: "/hash-comparison", category: "security", isFree: true, isFeatured: false },
  { id: "random-password-phrase", name: "Random Password Phrase", description: "Generate memorable but secure passphrases using word lists. Combine random words with separators for passwords that are both strong and easy to remember.", url: "/random-password-phrase", category: "security", isFree: true, isFeatured: false },
  { id: "ssl-expiry-checker", name: "SSL Expiry Checker", description: "Check SSL certificate expiration dates for multiple domains. Get days-until-expiry counts and email-ready summary reports for certificate renewal planning.", url: "/ssl-expiry-checker", category: "security", isFree: true, isFeatured: false },
  { id: "xss-scanner", name: "XSS Scanner", description: "Test URLs and form inputs for reflected XSS vulnerabilities. Encode and decode common XSS payloads with HTML, URL, JavaScript, and Base64 encoding.", url: "/xss-scanner", category: "security", isFree: true, isFeatured: false },
  { id: "api-key-generator", name: "API Key Generator", description: "Generate cryptographically secure API keys with configurable prefixes, formats, and character sets. Create keys for REST APIs, SDKs, and authentication tokens.", url: "/api-key-generator", category: "security", isFree: true, isFeatured: false },
  { id: "network-security", name: "Network Security Scanner", description: "Scan network security configurations including open ports, SSL/TLS settings, DNS security, and HTTP security headers. Get a comprehensive security posture report.", url: "/network-security", category: "security", isFree: true, isFeatured: false },

  // ── AI Tools ────────────────────────────────────────────────
  { id: "ai-text-summarizer", name: "AI Text Summarizer", description: "Summarize long articles, documents, and text passages. Extract key sentences and main ideas using extractive summarization techniques.", url: "/ai-text-summarizer", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-rewriter", name: "AI Rewriter", description: "Rewrite sentences and paragraphs with different tones and styles. Paraphrase content for clarity, formality, or simplicity while preserving original meaning.", url: "/ai-rewriter", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-readability-score", name: "AI Readability Score", description: "Measure text readability with Flesch-Kincaid, Gunning Fog, SMOG, and Coleman-Liau indexes. Get grade-level scores and readability improvement suggestions.", url: "/ai-readability-score", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-sentiment-analysis", name: "AI Sentiment Analysis", description: "Analyze the emotional tone of text. Detect positive, negative, and neutral sentiment with keyword-based analysis and intensity scoring.", url: "/ai-sentiment-analysis", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-keyword-extractor", name: "AI Keyword Extractor", description: "Extract key terms, phrases, and concepts from any text. Get keyword frequency counts and relevance scoring for SEO content optimization.", url: "/ai-keyword-extractor", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-grammar-checker", name: "AI Grammar Checker", description: "Check text for grammar, spelling, and punctuation errors. Get suggestions for corrections with rule-based grammar checking and style recommendations.", url: "/ai-grammar-checker", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-plagiarism-checker", name: "AI Plagiarism Checker", description: "Compare text against web sources to detect potential plagiarism. Get similarity scores and source references for academic and content integrity checking.", url: "/ai-plagiarism-checker", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-title-generator", name: "AI Title Generator", description: "Generate compelling titles, headlines, and subject lines. Create click-worthy titles for blog posts, articles, YouTube videos, and email campaigns.", url: "/ai-title-generator", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-meta-description", name: "AI Meta Description Generator", description: "Generate SEO-optimized meta descriptions for any webpage. Create compelling snippets with target keywords and optimal character length for search results.", url: "/ai-meta-description", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-hashtag-generator", name: "AI Hashtag Generator", description: "Generate relevant hashtags for social media posts. Get trending and niche hashtag suggestions for Instagram, Twitter, LinkedIn, and TikTok.", url: "/ai-hashtag-generator", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-content-generator", name: "AI Content Generator", description: "Generate high-quality blog posts, articles, and marketing copy. Create unique content on any topic with customizable tone, length, and format options.", url: "/ai-content-generator", category: "ai", isFree: true, isFeatured: false },
  { id: "ai-paraphrasing-tool", name: "AI Paraphrasing Tool", description: "Paraphrase sentences and paragraphs while preserving meaning. Rewrite content with different vocabulary, sentence structure, and readability levels.", url: "/ai-paraphrasing-tool", category: "ai", isFree: true, isFeatured: false },

  // ── Developer Tools ─────────────────────────────────────────
  { id: "base64-decoder", name: "Base64 Decoder", description: "Decode Base64-encoded strings back to readable text or binary data. Supports standard and URL-safe Base64 decoding with character set detection.", url: "/base64-decoder", category: "code-dev", isFree: true, isFeatured: false },
  { id: "html-decoder", name: "HTML Decoder", description: "Decode HTML-encoded text back to plain characters. Unescape HTML entities, remove HTML tags, and convert encoded text to readable format.", url: "/html-decoder", category: "code-dev", isFree: true, isFeatured: false },
  { id: "json-validator", name: "JSON Validator", description: "Validate JSON data with detailed error messages. Check syntax, structure, and data types with line-level error reporting and beautification.", url: "/json-validator", category: "code-dev", isFree: true, isFeatured: false },
  { id: "yaml-formatter", name: "YAML Formatter", description: "Format and beautify YAML files. Fix indentation, align values, and validate YAML syntax for configuration files, CI/CD pipelines, and data serialization.", url: "/yaml-formatter", category: "code-dev", isFree: true, isFeatured: false },
  { id: "xml-formatter", name: "XML Formatter", description: "Format and beautify XML documents with proper indentation. Validate XML syntax, collapse/expand nodes, and navigate complex XML structures.", url: "/xml-formatter", category: "code-dev", isFree: true, isFeatured: false },
  { id: "csv-formatter", name: "CSV Formatter", description: "Format and clean CSV data. Fix delimiter issues, handle quoted fields, align columns, and preview tabular data before exporting.", url: "/csv-formatter", category: "code-dev", isFree: true, isFeatured: false },
  { id: "css-prefixer", name: "CSS Vendor Prefixer", description: "Add vendor prefixes to CSS properties automatically. Generate cross-browser compatible CSS with -webkit-, -moz-, -ms-, and -o- prefixes for maximum browser support.", url: "/css-prefixer", category: "code-dev", isFree: true, isFeatured: false },
  { id: "js-beautifier", name: "JS Beautifier", description: "Beautify and format JavaScript code. Fix indentation, add semicolons, and restructure minified code with configurable formatting options.", url: "/js-beautifier", category: "code-dev", isFree: true, isFeatured: false },
  { id: "json-to-typescript", name: "JSON to TypeScript", description: "Convert JSON objects to TypeScript interfaces and type definitions. Generate strongly-typed interfaces from sample JSON data for type-safe development.", url: "/json-to-typescript", category: "code-dev", isFree: true, isFeatured: false },
  { id: "css-selector-tester", name: "CSS Selector Tester", description: "Test CSS selectors against HTML content. Match elements visually and debug complex selectors, pseudo-classes, and combinators in real time.", url: "/css-selector-tester", category: "code-dev", isFree: true, isFeatured: false },
  { id: "api-tester", name: "API Tester", description: "Test REST APIs with customizable HTTP methods, headers, query parameters, and request bodies. View response status codes, headers, and formatted response data.", url: "/api-tester", category: "code-dev", isFree: true, isFeatured: false },
  { id: "readme-generator", name: "README Generator", description: "Generate professional GitHub README files. Add project descriptions, installation instructions, badges, usage examples, and contribution guidelines.", url: "/readme-generator", category: "code-dev", isFree: true, isFeatured: false },

  // ── More Text Tools ─────────────────────────────────────────
  { id: "alphabetizer", name: "Alphabetizer", description: "Sort text alphabetically with advanced options. Sort by last word, by line length, in reverse order, or remove duplicates while sorting.", url: "/alphabetizer", category: "text-writing", isFree: true, isFeatured: false },
  { id: "character-counter", name: "Character Counter", description: "Count characters, words, sentences, and paragraphs in real time. Track character limits for social media, SEO meta descriptions, and SMS messages.", url: "/character-counter", category: "text-writing", isFree: true, isFeatured: false },
  { id: "palindrome-checker", name: "Palindrome Checker", description: "Check if a word, phrase, or number is a palindrome. Ignore spaces, punctuation, and case with detailed palindrome analysis and reversal display.", url: "/palindrome-checker", category: "text-writing", isFree: true, isFeatured: false },
  { id: "anagram-finder", name: "Anagram Finder", description: "Find all anagrams for a given word or phrase. Discover word permutations and solve crossword puzzles with the built-in anagram dictionary.", url: "/anagram-finder", category: "text-writing", isFree: true, isFeatured: false },
  { id: "text-to-binary", name: "Text to Binary Converter", description: "Convert text to binary code and binary to text. Translate ASCII and Unicode characters to binary representation for encoding and encryption learning.", url: "/text-to-binary", category: "text-writing", isFree: true, isFeatured: false },
  { id: "boggle-solver", name: "Boggle Solver", description: "Find all valid words in a Boggle board. Enter your board letters and discover every possible word with scoring and definition links.", url: "/boggle-solver", category: "text-writing", isFree: true, isFeatured: false },
  { id: "morse-code", name: "Morse Code Converter", description: "Convert text to Morse code and Morse code back to text. Learn Morse code with audio playback, timing controls, and signal visualization.", url: "/morse-code", category: "text-writing", isFree: true, isFeatured: false },
  { id: "pig-latin", name: "Pig Latin Translator", description: "Translate text to Pig Latin and back. Convert English words and sentences to Pig Latin following the standard transformation rules.", url: "/pig-latin", category: "text-writing", isFree: true, isFeatured: false },
  { id: "word-scrambler", name: "Word Scrambler", description: "Scramble words randomly while keeping first and last letters intact. Create word puzzles and games with customizable scrambling intensity.", url: "/word-scrambler", category: "text-writing", isFree: true, isFeatured: false },
  { id: "text-repeater", name: "Text Repeater", description: "Repeat any text multiple times with customizable separators. Generate repeated lines for testing, templates, and data generation with optional prefix/suffix.", url: "/text-repeater", category: "text-writing", isFree: true, isFeatured: false },

  // ── Image Tools ─────────────────────────────────────────────
  { id: "image-rotator", name: "Image Rotator", description: "Rotate images by 90, 180, or 270 degrees, or at any custom angle. Flip images horizontally and vertically with preview and download.", url: "/image-rotator", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-inverter", name: "Image Inverter", description: "Invert image colors to create negative effects. Apply color inversion with adjustable intensity for creative photo editing and accessibility testing.", url: "/image-inverter", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-flipper", name: "Image Flipper", description: "Flip images horizontally or vertically. Create mirror effects for photos, correct orientation, and preview before downloading.", url: "/image-flipper", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-to-pencil-sketch", name: "Image to Pencil Sketch", description: "Convert photos to pencil sketch effects. Transform your images into artistic sketches with adjustable intensity and stroke detail.", url: "/image-to-pencil-sketch", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-sepia", name: "Image Sepia Filter", description: "Apply vintage sepia tone effects to photos. Create old-fashioned, warm-toned images with adjustable sepia intensity for retro photography aesthetics.", url: "/image-sepia", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-saturation", name: "Image Saturation Adjuster", description: "Adjust image saturation levels. Increase or decrease color intensity to create vivid or desaturated effects with real-time preview.", url: "/image-saturation", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-brightness", name: "Image Brightness Adjuster", description: "Adjust image brightness and contrast levels. Lighten or darken photos with real-time preview and fine-grained slider controls.", url: "/image-brightness", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-color-picker", name: "Image Color Picker", description: "Pick colors from any image. Upload an image, click on any pixel, and get HEX, RGB, and HSL color values instantly.", url: "/image-color-picker", category: "image-design", isFree: true, isFeatured: false },
  { id: "collage-maker", name: "Collage Maker", description: "Create photo collages from multiple images. Choose grid layouts, adjust spacing, and add borders to create beautiful image compositions.", url: "/collage-maker", category: "image-design", isFree: true, isFeatured: false },
  { id: "image-to-ico", name: "Image to ICO Converter", description: "Convert images to ICO format for favicons and Windows icons. Generate multiple sizes (16x16 to 256x256) in a single ICO file.", url: "/image-to-ico", category: "image-design", isFree: true, isFeatured: false },
  { id: "color-palette", name: "Color Palette Generator", description: "Generate beautiful color palettes from any starting color. Create monochromatic, complementary, analogous, and triadic schemes with HEX and RGB values.", url: "/color-palette", category: "image-design", isFree: true, isFeatured: false },
  { id: "add-text-to-image-online", name: "Add Text to Image", description: "Add custom text overlays to any image. Choose font, size, color, position, and rotation with real-time preview and download.", url: "/add-text-to-image-online", category: "image-design", isFree: true, isFeatured: false },

  // ── SEO Tools ───────────────────────────────────────────────
  { id: "keyword-density", name: "Keyword Density Checker", description: "Analyze keyword density in any text. Identify overused and underused keywords with frequency analysis and optimization recommendations.", url: "/keyword-density", category: "seo", isFree: true, isFeatured: false },
  { id: "seo-audit", name: "SEO Audit Tool", description: "Run a basic SEO audit on any webpage. Check meta tags, headings, images, links, and structure with actionable optimization suggestions.", url: "/seo-audit", category: "seo", isFree: true, isFeatured: false },
  { id: "page-speed-checker", name: "Page Speed Checker", description: "Check webpage load time and performance. Get speed metrics, Core Web Vitals assessment, and optimization recommendations for faster loading.", url: "/page-speed-checker", category: "seo", isFree: true, isFeatured: false },
  { id: "backlink-checker", name: "Backlink Checker", description: "Check backlinks pointing to any URL. Discover link sources, anchor text distribution, and link authority for SEO link building analysis.", url: "/backlink-checker", category: "seo", isFree: true, isFeatured: false },
  { id: "seo-title-preview", name: "SEO Title Preview", description: "Preview how your title tag appears in Google search results. Test title lengths, character counts, and pixel widths for maximum SERP visibility.", url: "/seo-title-preview", category: "seo", isFree: true, isFeatured: false },
  { id: "keyword-suggestion", name: "Keyword Suggestion Tool", description: "Generate keyword suggestions and related search terms. Find long-tail keyword opportunities for SEO content planning and PPC campaign optimization.", url: "/keyword-suggestion", category: "seo", isFree: true, isFeatured: false },
  { id: "google-index-checker", name: "Google Index Checker", description: "Check if a URL is indexed in Google search results. Verify index status, cached version dates, and indexed page count for any website.", url: "/google-index-checker", category: "seo", isFree: true, isFeatured: false },
  { id: "page-authority", name: "Page Authority Checker", description: "Estimate page authority and domain authority scores. Get comparative strength metrics for any webpage against competitors and industry benchmarks.", url: "/page-authority", category: "seo", isFree: true, isFeatured: false },
  { id: "robots-txt-validator", name: "Robots.txt Validator", description: "Validate your robots.txt file for syntax errors and testing. Check if specific URLs are blocked for search engine crawlers with path matching.", url: "/robots-txt-validator", category: "seo", isFree: true, isFeatured: false },
  { id: "social-preview", name: "Social Media Preview", description: "Preview how your webpage appears when shared on social media. Check OG tags, Twitter cards, and rich previews for Facebook, Twitter, LinkedIn, and Slack.", url: "/social-preview", category: "seo", isFree: true, isFeatured: false },
  { id: "mobile-friendly-test", name: "Mobile Friendly Test", description: "Test if your website is mobile-friendly and responsive. Check viewport configuration, tap target sizes, font legibility, and content width on mobile screens.", url: "/mobile-friendly-test", category: "seo", isFree: true, isFeatured: false },

  // ── Converters ──────────────────────────────────────────────
  { id: "csv-to-json", name: "CSV to JSON Converter", description: "Convert CSV data to JSON format online. Handle headers, delimiters, and quoted fields with customizable output formatting.", url: "/csv-to-json", category: "converters", isFree: true, isFeatured: false },
  { id: "json-to-xml", name: "JSON to XML Converter", description: "Convert JSON data to XML format. Handle nested objects, arrays, and attributes with configurable root element names.", url: "/json-to-xml", category: "converters", isFree: true, isFeatured: false },
  { id: "xml-to-csv", name: "XML to CSV Converter", description: "Convert XML data to CSV format. Flatten nested XML structures into tabular data with customizable field mapping and delimiter options.", url: "/xml-to-csv", category: "converters", isFree: true, isFeatured: false },
  { id: "rgb-to-hex", name: "RGB to HEX Converter", description: "Convert RGB color values to HEX and back. Preview colors, get CSS-ready code, and save frequently used colors with named references.", url: "/rgb-to-hex", category: "converters", isFree: true, isFeatured: false },
  { id: "markdown-to-html", name: "Markdown to HTML Converter", description: "Convert Markdown text to clean HTML code. Supports headings, lists, code blocks, tables, images, and links with syntax highlighting.", url: "/markdown-to-html", category: "converters", isFree: true, isFeatured: false },
  { id: "html-to-markdown", name: "HTML to Markdown Converter", description: "Convert HTML code back to Markdown format. Clean and simple conversion with support for common HTML elements and nesting.", url: "/html-to-markdown", category: "converters", isFree: true, isFeatured: false },
  { id: "pdf-to-png", name: "PDF to PNG Converter", description: "Convert PDF pages to high-quality PNG images. Select page range, set resolution, and download individual pages or all pages as images.", url: "/pdf-to-png", category: "converters", isFree: true, isFeatured: false },
  { id: "png-to-jpg", name: "PNG to JPG Converter", description: "Convert PNG images to JPG format. Adjust quality settings, choose background color for transparent PNGs, and batch convert multiple files.", url: "/png-to-jpg", category: "converters", isFree: true, isFeatured: false },
  { id: "webp-to-png", name: "WebP to PNG Converter", description: "Convert WebP images to PNG format. Maintain transparency and quality while converting the modern WebP format to universally compatible PNG.", url: "/webp-to-png", category: "converters", isFree: true, isFeatured: false },
  { id: "svg-to-png", name: "SVG to PNG Converter", description: "Convert SVG vector graphics to PNG raster images. Set output dimensions, background color, and resolution for production-ready raster assets.", url: "/svg-to-png", category: "converters", isFree: true, isFeatured: false },
  { id: "gif-to-mp4", name: "GIF to MP4 Converter", description: "Convert animated GIFs to MP4 video format. Reduce file size significantly while maintaining animation quality with configurable frame rate and quality.", url: "/gif-to-mp4", category: "converters", isFree: true, isFeatured: false },
  { id: "temperature-converter", name: "Temperature Converter", description: "Convert temperatures between Celsius, Fahrenheit, Kelvin, and Rankine. Get conversion formulas and instant results with decimal precision.", url: "/temperature-converter", category: "converters", isFree: true, isFeatured: false },
  { id: "number-to-words", name: "Number to Words Converter", description: "Convert numbers to English words. Write any number in words for checks, invoices, legal documents, and educational purposes.", url: "/number-to-words", category: "converters", isFree: true, isFeatured: false },

  // ── More PDF Tools ──────────────────────────────────────────
  { id: "pdf-to-text", name: "PDF to Text Extractor", description: "Extract text content from PDF files. Copy text from any PDF with page-by-page extraction and preserve paragraph structure and formatting.", url: "/pdf-to-text", category: "productivity", isFree: true, isFeatured: false },
  { id: "pdf-to-excel", name: "PDF to Excel Converter", description: "Convert PDF tables to Excel spreadsheets. Extract tabular data from PDFs with column alignment and export as .xlsx or .csv format.", url: "/pdf-to-excel", category: "productivity", isFree: true, isFeatured: false },
  { id: "pdf-metadata-editor", name: "PDF Metadata Editor", description: "View and edit PDF metadata including title, author, subject, and keywords. Update document properties for better file organization and searchability.", url: "/pdf-metadata-editor", category: "productivity", isFree: true, isFeatured: false },
  { id: "pdf-page-number", name: "PDF Page Numberer", description: "Add page numbers to PDF documents. Customize position, format, starting number, and font for professional document pagination.", url: "/pdf-page-number", category: "productivity", isFree: true, isFeatured: false },
  { id: "pdf-compare", name: "PDF Comparison Tool", description: "Compare two PDF files and highlight differences. Detect added, removed, and modified content between document versions with visual diff overlays.", url: "/pdf-compare", category: "productivity", isFree: true, isFeatured: false },
  { id: "pdf-to-html", name: "PDF to HTML Converter", description: "Convert PDF files to HTML web pages. Extract text, images, and basic formatting into clean, responsive HTML code for web publishing.", url: "/pdf-to-html", category: "productivity", isFree: true, isFeatured: false },

  // ── More Network Tools ──────────────────────────────────────
  { id: "ipv4-ipv6-converter", name: "IPv4 to IPv6 Converter", description: "Convert IPv4 addresses to IPv6 mapped addresses and back. Generate 6to4, Teredo, and ISATAP addresses from standard IPv4 notation.", url: "/ipv4-ipv6-converter", category: "network-internet", isFree: true, isFeatured: false },
  { id: "mac-address-lookup", name: "MAC Address Lookup", description: "Look up the manufacturer or vendor of any MAC address using the OUI (Organizationally Unique Identifier) database.", url: "/mac-address-lookup", category: "network-internet", isFree: true, isFeatured: false },
  { id: "traceroute", name: "Traceroute Tool", description: "Trace the network path from your browser to any host. Visualize every hop with IP addresses, latency, and geographic location data.", url: "/traceroute", category: "network-internet", isFree: true, isFeatured: false },
  { id: "bandwidth-calculator", name: "Bandwidth Calculator", description: "Calculate bandwidth requirements based on data size and transfer time. Estimate download/upload times and required connection speeds for any file transfer.", url: "/bandwidth-calculator", category: "network-internet", isFree: true, isFeatured: false },
  { id: "speed-test", name: "Speed Test", description: "Test your internet connection speed. Measure download speed, upload speed, and ping latency with detailed performance metrics and results history.", url: "/speed-test", category: "network-internet", isFree: true, isFeatured: false },
  { id: "uptime-checker", name: "Uptime Checker", description: "Check if a website or server is currently online and accessible. Get response time, status code, and historical uptime data for monitoring reliability.", url: "/uptime-checker", category: "network-internet", isFree: true, isFeatured: false },

  // ── Audio & Video Tools ──────────────────────────────────────
  { id: "audio-converter", name: "Audio Converter", description: "Convert audio files between MP3, WAV, FLAC, AAC, and OGG formats. Batch convert with customizable bitrate, sample rate, and channel options.", url: "/audio-converter", category: "audio-video", isFree: true, isFeatured: false },
  { id: "video-compressor", name: "Video Compressor", description: "Reduce video file size without losing noticeable quality. Adjust compression level, resolution, and bitrate for web-optimized video output.", url: "/video-compressor", category: "audio-video", isFree: true, isFeatured: false },
  { id: "mp3-cutter", name: "MP3 Cutter", description: "Cut and trim MP3 audio files with precision. Select start and end timestamps to extract your favorite segments from any audio track.", url: "/mp3-cutter", category: "audio-video", isFree: true, isFeatured: false },
  { id: "video-to-gif", name: "Video to GIF Converter", description: "Convert video clips to animated GIFs. Set start time, duration, frame rate, and dimensions to create lightweight, shareable animations.", url: "/video-to-gif", category: "audio-video", isFree: true, isFeatured: false },
  { id: "audio-merger", name: "Audio Merger", description: "Merge multiple audio files into one seamless track. Combine songs, recordings, or voiceovers with crossfade support and custom output order.", url: "/audio-merger", category: "audio-video", isFree: true, isFeatured: false },
  { id: "video-resizer", name: "Video Resizer", description: "Change video dimensions and aspect ratio. Resize to standard resolutions like 1080p, 720p, or custom dimensions while maintaining quality.", url: "/video-resizer", category: "audio-video", isFree: true, isFeatured: false },
  { id: "audio-extractor", name: "Audio Extractor", description: "Extract audio tracks from video files. Save the soundtrack from any video as MP3, WAV, or AAC with customizable output quality settings.", url: "/audio-extractor", category: "audio-video", isFree: true, isFeatured: false },
  { id: "volume-booster", name: "Volume Booster", description: "Increase audio volume of any media file. Boost audio levels by up to 300% without clipping, with real-time preview and normalization options.", url: "/volume-booster", category: "audio-video", isFree: true, isFeatured: false },
  { id: "video-to-mp3", name: "Video to MP3 Converter", description: "Convert video files to MP3 audio. Extract high-quality audio from MP4, AVI, MOV, and other video formats for music and podcast listening.", url: "/video-to-mp3", category: "audio-video", isFree: true, isFeatured: false },
  { id: "screen-recorder", name: "Screen Recorder", description: "Record your computer screen with audio. Capture browser tabs, applications, or entire desktop with microphone or system audio for tutorials and demos.", url: "/screen-recorder", category: "audio-video", isFree: true, isFeatured: false },
  { id: "video-converter", name: "Video Converter", description: "Convert video files between MP4, AVI, MOV, MKV, WebM, and more. Customize resolution, bitrate, frame rate, and codec for any device or platform.", url: "/video-converter", category: "audio-video", isFree: true, isFeatured: false },
];
