export interface HtmlEntity {
  entity: string;
  character: string;
  codePoint: number;
  name: string;
  category: string;
}

export const HTML_ENTITIES: HtmlEntity[] = [
  // Basic punctuation
  { entity: "&quot;", character: "\"", codePoint: 34, name: "quotation mark", category: "punctuation" },
  { entity: "&amp;", character: "&", codePoint: 38, name: "ampersand", category: "punctuation" },
  { entity: "&apos;", character: "'", codePoint: 39, name: "apostrophe", category: "punctuation" },
  { entity: "&lt;", character: "<", codePoint: 60, name: "less-than", category: "punctuation" },
  { entity: "&gt;", character: ">", codePoint: 62, name: "greater-than", category: "punctuation" },
  { entity: "&nbsp;", character: "\u00A0", codePoint: 160, name: "non-breaking space", category: "punctuation" },
  { entity: "&iexcl;", character: "\u00A1", codePoint: 161, name: "inverted exclamation mark", category: "punctuation" },
  { entity: "&cent;", character: "\u00A2", codePoint: 162, name: "cent sign", category: "currency" },
  { entity: "&pound;", character: "\u00A3", codePoint: 163, name: "pound sign", category: "currency" },
  { entity: "&curren;", character: "\u00A4", codePoint: 164, name: "currency sign", category: "currency" },
  { entity: "&yen;", character: "\u00A5", codePoint: 165, name: "yen sign", category: "currency" },
  { entity: "&brvbar;", character: "\u00A6", codePoint: 166, name: "broken bar", category: "punctuation" },
  { entity: "&sect;", character: "\u00A7", codePoint: 167, name: "section sign", category: "punctuation" },
  { entity: "&uml;", character: "\u00A8", codePoint: 168, name: "diaeresis", category: "diacritical" },
  { entity: "&copy;", character: "\u00A9", codePoint: 169, name: "copyright sign", category: "legal" },
  { entity: "&ordf;", character: "\u00AA", codePoint: 170, name: "feminine ordinal indicator", category: "punctuation" },
  { entity: "&laquo;", character: "\u00AB", codePoint: 171, name: "left-pointing double angle quotation mark", category: "quotes" },
  { entity: "&not;", character: "\u00AC", codePoint: 172, name: "not sign", category: "math" },
  { entity: "&shy;", character: "\u00AD", codePoint: 173, name: "soft hyphen", category: "punctuation" },
  { entity: "&reg;", character: "\u00AE", codePoint: 174, name: "registered sign", category: "legal" },
  { entity: "&macr;", character: "\u00AF", codePoint: 175, name: "macron", category: "diacritical" },
  { entity: "&deg;", character: "\u00B0", codePoint: 176, name: "degree sign", category: "math" },
  { entity: "&plusmn;", character: "\u00B1", codePoint: 177, name: "plus-minus sign", category: "math" },
  { entity: "&sup2;", character: "\u00B2", codePoint: 178, name: "superscript two", category: "math" },
  { entity: "&sup3;", character: "\u00B3", codePoint: 179, name: "superscript three", category: "math" },
  { entity: "&acute;", character: "\u00B4", codePoint: 180, name: "acute accent", category: "diacritical" },
  { entity: "&micro;", character: "\u00B5", codePoint: 181, name: "micro sign", category: "math" },
  { entity: "&para;", character: "\u00B6", codePoint: 182, name: "pilcrow sign", category: "punctuation" },
  { entity: "&middot;", character: "\u00B7", codePoint: 183, name: "middle dot", category: "punctuation" },
  { entity: "&cedil;", character: "\u00B8", codePoint: 184, name: "cedilla", category: "diacritical" },
  { entity: "&sup1;", character: "\u00B9", codePoint: 185, name: "superscript one", category: "math" },
  { entity: "&ordm;", character: "\u00BA", codePoint: 186, name: "masculine ordinal indicator", category: "punctuation" },
  { entity: "&raquo;", character: "\u00BB", codePoint: 187, name: "right-pointing double angle quotation mark", category: "quotes" },
  { entity: "&frac14;", character: "\u00BC", codePoint: 188, name: "vulgar fraction one quarter", category: "math" },
  { entity: "&frac12;", character: "\u00BD", codePoint: 189, name: "vulgar fraction one half", category: "math" },
  { entity: "&frac34;", character: "\u00BE", codePoint: 190, name: "vulgar fraction three quarters", category: "math" },
  { entity: "&iquest;", character: "\u00BF", codePoint: 191, name: "inverted question mark", category: "punctuation" },
  // Latin letters
  { entity: "&Agrave;", character: "\u00C0", codePoint: 192, name: "Latin capital letter A with grave", category: "latin" },
  { entity: "&Aacute;", character: "\u00C1", codePoint: 193, name: "Latin capital letter A with acute", category: "latin" },
  { entity: "&Acirc;", character: "\u00C2", codePoint: 194, name: "Latin capital letter A with circumflex", category: "latin" },
  { entity: "&Atilde;", character: "\u00C3", codePoint: 195, name: "Latin capital letter A with tilde", category: "latin" },
  { entity: "&Auml;", character: "\u00C4", codePoint: 196, name: "Latin capital letter A with diaeresis", category: "latin" },
  { entity: "&Aring;", character: "\u00C5", codePoint: 197, name: "Latin capital letter A with ring above", category: "latin" },
  { entity: "&AElig;", character: "\u00C6", codePoint: 198, name: "Latin capital letter AE", category: "latin" },
  { entity: "&Ccedil;", character: "\u00C7", codePoint: 199, name: "Latin capital letter C with cedilla", category: "latin" },
  { entity: "&Egrave;", character: "\u00C8", codePoint: 200, name: "Latin capital letter E with grave", category: "latin" },
  { entity: "&Eacute;", character: "\u00C9", codePoint: 201, name: "Latin capital letter E with acute", category: "latin" },
  { entity: "&Ecirc;", character: "\u00CA", codePoint: 202, name: "Latin capital letter E with circumflex", category: "latin" },
  { entity: "&Euml;", character: "\u00CB", codePoint: 203, name: "Latin capital letter E with diaeresis", category: "latin" },
  { entity: "&Igrave;", character: "\u00CC", codePoint: 204, name: "Latin capital letter I with grave", category: "latin" },
  { entity: "&Iacute;", character: "\u00CD", codePoint: 205, name: "Latin capital letter I with acute", category: "latin" },
  { entity: "&Icirc;", character: "\u00CE", codePoint: 206, name: "Latin capital letter I with circumflex", category: "latin" },
  { entity: "&Iuml;", character: "\u00CF", codePoint: 207, name: "Latin capital letter I with diaeresis", category: "latin" },
  { entity: "&ETH;", character: "\u00D0", codePoint: 208, name: "Latin capital letter Eth", category: "latin" },
  { entity: "&Ntilde;", character: "\u00D1", codePoint: 209, name: "Latin capital letter N with tilde", category: "latin" },
  { entity: "&Ograve;", character: "\u00D2", codePoint: 210, name: "Latin capital letter O with grave", category: "latin" },
  { entity: "&Oacute;", character: "\u00D3", codePoint: 211, name: "Latin capital letter O with acute", category: "latin" },
  { entity: "&Ocirc;", character: "\u00D4", codePoint: 212, name: "Latin capital letter O with circumflex", category: "latin" },
  { entity: "&Otilde;", character: "\u00D5", codePoint: 213, name: "Latin capital letter O with tilde", category: "latin" },
  { entity: "&Ouml;", character: "\u00D6", codePoint: 214, name: "Latin capital letter O with diaeresis", category: "latin" },
  { entity: "&times;", character: "\u00D7", codePoint: 215, name: "multiplication sign", category: "math" },
  { entity: "&Oslash;", character: "\u00D8", codePoint: 216, name: "Latin capital letter O with stroke", category: "latin" },
  { entity: "&Ugrave;", character: "\u00D9", codePoint: 217, name: "Latin capital letter U with grave", category: "latin" },
  { entity: "&Uacute;", character: "\u00DA", codePoint: 218, name: "Latin capital letter U with acute", category: "latin" },
  { entity: "&Ucirc;", character: "\u00DB", codePoint: 219, name: "Latin capital letter U with circumflex", category: "latin" },
  { entity: "&Uuml;", character: "\u00DC", codePoint: 220, name: "Latin capital letter U with diaeresis", category: "latin" },
  { entity: "&Yacute;", character: "\u00DD", codePoint: 221, name: "Latin capital letter Y with acute", category: "latin" },
  { entity: "&THORN;", character: "\u00DE", codePoint: 222, name: "Latin capital letter Thorn", category: "latin" },
  { entity: "&szlig;", character: "\u00DF", codePoint: 223, name: "Latin small letter sharp s", category: "latin" },
  { entity: "&agrave;", character: "\u00E0", codePoint: 224, name: "Latin small letter a with grave", category: "latin" },
  { entity: "&aacute;", character: "\u00E1", codePoint: 225, name: "Latin small letter a with acute", category: "latin" },
  { entity: "&acirc;", character: "\u00E2", codePoint: 226, name: "Latin small letter a with circumflex", category: "latin" },
  { entity: "&atilde;", character: "\u00E3", codePoint: 227, name: "Latin small letter a with tilde", category: "latin" },
  { entity: "&auml;", character: "\u00E4", codePoint: 228, name: "Latin small letter a with diaeresis", category: "latin" },
  { entity: "&aring;", character: "\u00E5", codePoint: 229, name: "Latin small letter a with ring above", category: "latin" },
  { entity: "&aelig;", character: "\u00E6", codePoint: 230, name: "Latin small letter ae", category: "latin" },
  { entity: "&ccedil;", character: "\u00E7", codePoint: 231, name: "Latin small letter c with cedilla", category: "latin" },
  { entity: "&egrave;", character: "\u00E8", codePoint: 232, name: "Latin small letter e with grave", category: "latin" },
  { entity: "&eacute;", character: "\u00E9", codePoint: 233, name: "Latin small letter e with acute", category: "latin" },
  { entity: "&ecirc;", character: "\u00EA", codePoint: 234, name: "Latin small letter e with circumflex", category: "latin" },
  { entity: "&euml;", character: "\u00EB", codePoint: 235, name: "Latin small letter e with diaeresis", category: "latin" },
  { entity: "&igrave;", character: "\u00EC", codePoint: 236, name: "Latin small letter i with grave", category: "latin" },
  { entity: "&iacute;", character: "\u00ED", codePoint: 237, name: "Latin small letter i with acute", category: "latin" },
  { entity: "&icirc;", character: "\u00EE", codePoint: 238, name: "Latin small letter i with circumflex", category: "latin" },
  { entity: "&iuml;", character: "\u00EF", codePoint: 239, name: "Latin small letter i with diaeresis", category: "latin" },
  { entity: "&eth;", character: "\u00F0", codePoint: 240, name: "Latin small letter eth", category: "latin" },
  { entity: "&ntilde;", character: "\u00F1", codePoint: 241, name: "Latin small letter n with tilde", category: "latin" },
  { entity: "&ograve;", character: "\u00F2", codePoint: 242, name: "Latin small letter o with grave", category: "latin" },
  { entity: "&oacute;", character: "\u00F3", codePoint: 243, name: "Latin small letter o with acute", category: "latin" },
  { entity: "&ocirc;", character: "\u00F4", codePoint: 244, name: "Latin small letter o with circumflex", category: "latin" },
  { entity: "&otilde;", character: "\u00F5", codePoint: 245, name: "Latin small letter o with tilde", category: "latin" },
  { entity: "&ouml;", character: "\u00F6", codePoint: 246, name: "Latin small letter o with diaeresis", category: "latin" },
  { entity: "&divide;", character: "\u00F7", codePoint: 247, name: "division sign", category: "math" },
  { entity: "&oslash;", character: "\u00F8", codePoint: 248, name: "Latin small letter o with stroke", category: "latin" },
  { entity: "&ugrave;", character: "\u00F9", codePoint: 249, name: "Latin small letter u with grave", category: "latin" },
  { entity: "&uacute;", character: "\u00FA", codePoint: 250, name: "Latin small letter u with acute", category: "latin" },
  { entity: "&ucirc;", character: "\u00FB", codePoint: 251, name: "Latin small letter u with circumflex", category: "latin" },
  { entity: "&uuml;", character: "\u00FC", codePoint: 252, name: "Latin small letter u with diaeresis", category: "latin" },
  { entity: "&yacute;", character: "\u00FD", codePoint: 253, name: "Latin small letter y with acute", category: "latin" },
  { entity: "&thorn;", character: "\u00FE", codePoint: 254, name: "Latin small letter thorn", category: "latin" },
  { entity: "&yuml;", character: "\u00FF", codePoint: 255, name: "Latin small letter y with diaeresis", category: "latin" },
  // Greek letters
  { entity: "&Alpha;", character: "\u0391", codePoint: 913, name: "Greek capital letter Alpha", category: "greek" },
  { entity: "&Beta;", character: "\u0392", codePoint: 914, name: "Greek capital letter Beta", category: "greek" },
  { entity: "&Gamma;", character: "\u0393", codePoint: 915, name: "Greek capital letter Gamma", category: "greek" },
  { entity: "&Delta;", character: "\u0394", codePoint: 916, name: "Greek capital letter Delta", category: "greek" },
  { entity: "&Epsilon;", character: "\u0395", codePoint: 917, name: "Greek capital letter Epsilon", category: "greek" },
  { entity: "&Zeta;", character: "\u0396", codePoint: 918, name: "Greek capital letter Zeta", category: "greek" },
  { entity: "&Eta;", character: "\u0397", codePoint: 919, name: "Greek capital letter Eta", category: "greek" },
  { entity: "&Theta;", character: "\u0398", codePoint: 920, name: "Greek capital letter Theta", category: "greek" },
  { entity: "&Iota;", character: "\u0399", codePoint: 921, name: "Greek capital letter Iota", category: "greek" },
  { entity: "&Kappa;", character: "\u039A", codePoint: 922, name: "Greek capital letter Kappa", category: "greek" },
  { entity: "&Lambda;", character: "\u039B", codePoint: 923, name: "Greek capital letter Lambda", category: "greek" },
  { entity: "&Mu;", character: "\u039C", codePoint: 924, name: "Greek capital letter Mu", category: "greek" },
  { entity: "&Nu;", character: "\u039D", codePoint: 925, name: "Greek capital letter Nu", category: "greek" },
  { entity: "&Xi;", character: "\u039E", codePoint: 926, name: "Greek capital letter Xi", category: "greek" },
  { entity: "&Omicron;", character: "\u039F", codePoint: 927, name: "Greek capital letter Omicron", category: "greek" },
  { entity: "&Pi;", character: "\u03A0", codePoint: 928, name: "Greek capital letter Pi", category: "greek" },
  { entity: "&Rho;", character: "\u03A1", codePoint: 929, name: "Greek capital letter Rho", category: "greek" },
  { entity: "&Sigma;", character: "\u03A3", codePoint: 931, name: "Greek capital letter Sigma", category: "greek" },
  { entity: "&Tau;", character: "\u03A4", codePoint: 932, name: "Greek capital letter Tau", category: "greek" },
  { entity: "&Upsilon;", character: "\u03A5", codePoint: 933, name: "Greek capital letter Upsilon", category: "greek" },
  { entity: "&Phi;", character: "\u03A6", codePoint: 934, name: "Greek capital letter Phi", category: "greek" },
  { entity: "&Chi;", character: "\u03A7", codePoint: 935, name: "Greek capital letter Chi", category: "greek" },
  { entity: "&Psi;", character: "\u03A8", codePoint: 936, name: "Greek capital letter Psi", category: "greek" },
  { entity: "&Omega;", character: "\u03A9", codePoint: 937, name: "Greek capital letter Omega", category: "greek" },
  { entity: "&alpha;", character: "\u03B1", codePoint: 945, name: "Greek small letter alpha", category: "greek" },
  { entity: "&beta;", character: "\u03B2", codePoint: 946, name: "Greek small letter beta", category: "greek" },
  { entity: "&gamma;", character: "\u03B3", codePoint: 947, name: "Greek small letter gamma", category: "greek" },
  { entity: "&delta;", character: "\u03B4", codePoint: 948, name: "Greek small letter delta", category: "greek" },
  { entity: "&epsilon;", character: "\u03B5", codePoint: 949, name: "Greek small letter epsilon", category: "greek" },
  { entity: "&zeta;", character: "\u03B6", codePoint: 950, name: "Greek small letter zeta", category: "greek" },
  { entity: "&eta;", character: "\u03B7", codePoint: 951, name: "Greek small letter eta", category: "greek" },
  { entity: "&theta;", character: "\u03B8", codePoint: 952, name: "Greek small letter theta", category: "greek" },
  { entity: "&iota;", character: "\u03B9", codePoint: 953, name: "Greek small letter iota", category: "greek" },
  { entity: "&kappa;", character: "\u03BA", codePoint: 954, name: "Greek small letter kappa", category: "greek" },
  { entity: "&lambda;", character: "\u03BB", codePoint: 955, name: "Greek small letter lambda", category: "greek" },
  { entity: "&mu;", character: "\u03BC", codePoint: 956, name: "Greek small letter mu", category: "greek" },
  { entity: "&nu;", character: "\u03BD", codePoint: 957, name: "Greek small letter nu", category: "greek" },
  { entity: "&xi;", character: "\u03BE", codePoint: 958, name: "Greek small letter xi", category: "greek" },
  { entity: "&omicron;", character: "\u03BF", codePoint: 959, name: "Greek small letter omicron", category: "greek" },
  { entity: "&pi;", character: "\u03C0", codePoint: 960, name: "Greek small letter pi", category: "greek" },
  { entity: "&rho;", character: "\u03C1", codePoint: 961, name: "Greek small letter rho", category: "greek" },
  { entity: "&sigmaf;", character: "\u03C2", codePoint: 962, name: "Greek small letter final sigma", category: "greek" },
  { entity: "&sigma;", character: "\u03C3", codePoint: 963, name: "Greek small letter sigma", category: "greek" },
  { entity: "&tau;", character: "\u03C4", codePoint: 964, name: "Greek small letter tau", category: "greek" },
  { entity: "&upsilon;", character: "\u03C5", codePoint: 965, name: "Greek small letter upsilon", category: "greek" },
  { entity: "&phi;", character: "\u03C6", codePoint: 966, name: "Greek small letter phi", category: "greek" },
  { entity: "&chi;", character: "\u03C7", codePoint: 967, name: "Greek small letter chi", category: "greek" },
  { entity: "&psi;", character: "\u03C8", codePoint: 968, name: "Greek small letter psi", category: "greek" },
  { entity: "&omega;", character: "\u03C9", codePoint: 969, name: "Greek small letter omega", category: "greek" },
  // Math symbols
  { entity: "&forall;", character: "\u2200", codePoint: 8704, name: "for all", category: "math" },
  { entity: "&part;", character: "\u2202", codePoint: 8706, name: "partial differential", category: "math" },
  { entity: "&exist;", character: "\u2203", codePoint: 8707, name: "there exists", category: "math" },
  { entity: "&empty;", character: "\u2205", codePoint: 8709, name: "empty set", category: "math" },
  { entity: "&nabla;", character: "\u2207", codePoint: 8711, name: "nabla", category: "math" },
  { entity: "&isin;", character: "\u2208", codePoint: 8712, name: "element of", category: "math" },
  { entity: "&notin;", character: "\u2209", codePoint: 8713, name: "not an element of", category: "math" },
  { entity: "&ni;", character: "\u220B", codePoint: 8715, name: "contains as member", category: "math" },
  { entity: "&prod;", character: "\u220F", codePoint: 8719, name: "n-ary product", category: "math" },
  { entity: "&sum;", character: "\u2211", codePoint: 8721, name: "n-ary summation", category: "math" },
  { entity: "&minus;", character: "\u2212", codePoint: 8722, name: "minus sign", category: "math" },
  { entity: "&lowast;", character: "\u2217", codePoint: 8727, name: "asterisk operator", category: "math" },
  { entity: "&radic;", character: "\u221A", codePoint: 8730, name: "square root", category: "math" },
  { entity: "&prop;", character: "\u221D", codePoint: 8733, name: "proportional to", category: "math" },
  { entity: "&infin;", character: "\u221E", codePoint: 8734, name: "infinity", category: "math" },
  { entity: "&ang;", character: "\u2220", codePoint: 8736, name: "angle", category: "math" },
  { entity: "&and;", character: "\u2227", codePoint: 8743, name: "logical and", category: "math" },
  { entity: "&or;", character: "\u2228", codePoint: 8744, name: "logical or", category: "math" },
  { entity: "&cap;", character: "\u2229", codePoint: 8745, name: "intersection", category: "math" },
  { entity: "&cup;", character: "\u222A", codePoint: 8746, name: "union", category: "math" },
  { entity: "&int;", character: "\u222B", codePoint: 8747, name: "integral", category: "math" },
  { entity: "&there4;", character: "\u2234", codePoint: 8756, name: "therefore", category: "math" },
  { entity: "&sim;", character: "\u223C", codePoint: 8764, name: "tilde operator", category: "math" },
  { entity: "&cong;", character: "\u2245", codePoint: 8773, name: "approximately equal to", category: "math" },
  { entity: "&asymp;", character: "\u2248", codePoint: 8776, name: "almost equal to", category: "math" },
  { entity: "&ne;", character: "\u2260", codePoint: 8800, name: "not equal to", category: "math" },
  { entity: "&equiv;", character: "\u2261", codePoint: 8801, name: "identical to", category: "math" },
  { entity: "&le;", character: "\u2264", codePoint: 8804, name: "less-than or equal to", category: "math" },
  { entity: "&ge;", character: "\u2265", codePoint: 8805, name: "greater-than or equal to", category: "math" },
  { entity: "&sub;", character: "\u2282", codePoint: 8834, name: "subset of", category: "math" },
  { entity: "&sup;", character: "\u2283", codePoint: 8835, name: "superset of", category: "math" },
  { entity: "&nsub;", character: "\u2284", codePoint: 8836, name: "not a subset of", category: "math" },
  { entity: "&sube;", character: "\u2286", codePoint: 8838, name: "subset of or equal to", category: "math" },
  { entity: "&supe;", character: "\u2287", codePoint: 8839, name: "superset of or equal to", category: "math" },
  { entity: "&oplus;", character: "\u2295", codePoint: 8853, name: "circled plus", category: "math" },
  { entity: "&otimes;", character: "\u2297", codePoint: 8855, name: "circled times", category: "math" },
  { entity: "&perp;", character: "\u22A5", codePoint: 8869, name: "up tack", category: "math" },
  { entity: "&sdot;", character: "\u22C5", codePoint: 8901, name: "dot operator", category: "math" },
  // Arrows
  { entity: "&larr;", character: "\u2190", codePoint: 8592, name: "leftwards arrow", category: "arrows" },
  { entity: "&uarr;", character: "\u2191", codePoint: 8593, name: "upwards arrow", category: "arrows" },
  { entity: "&rarr;", character: "\u2192", codePoint: 8594, name: "rightwards arrow", category: "arrows" },
  { entity: "&darr;", character: "\u2193", codePoint: 8595, name: "downwards arrow", category: "arrows" },
  { entity: "&harr;", character: "\u2194", codePoint: 8596, name: "left right arrow", category: "arrows" },
  { entity: "&crarr;", character: "\u21B5", codePoint: 8629, name: "downwards arrow with corner leftwards", category: "arrows" },
  { entity: "&lArr;", character: "\u21D0", codePoint: 8656, name: "leftwards double arrow", category: "arrows" },
  { entity: "&uArr;", character: "\u21D1", codePoint: 8657, name: "upwards double arrow", category: "arrows" },
  { entity: "&rArr;", character: "\u21D2", codePoint: 8658, name: "rightwards double arrow", category: "arrows" },
  { entity: "&dArr;", character: "\u21D3", codePoint: 8659, name: "downwards double arrow", category: "arrows" },
  { entity: "&hArr;", character: "\u21D4", codePoint: 8660, name: "left right double arrow", category: "arrows" },
  // Special characters
  { entity: "&bull;", character: "\u2022", codePoint: 8226, name: "bullet", category: "punctuation" },
  { entity: "&hellip;", character: "\u2026", codePoint: 8230, name: "horizontal ellipsis", category: "punctuation" },
  { entity: "&prime;", character: "\u2032", codePoint: 8242, name: "prime", category: "math" },
  { entity: "&Prime;", character: "\u2033", codePoint: 8243, name: "double prime", category: "math" },
  { entity: "&lsaquo;", character: "\u2039", codePoint: 8249, name: "single left-pointing angle quotation mark", category: "quotes" },
  { entity: "&rsaquo;", character: "\u203A", codePoint: 8250, name: "single right-pointing angle quotation mark", category: "quotes" },
  { entity: "&oline;", character: "\u203E", codePoint: 8254, name: "overline", category: "punctuation" },
  { entity: "&frasl;", character: "\u2044", codePoint: 8260, name: "fraction slash", category: "math" },
  { entity: "&euro;", character: "\u20AC", codePoint: 8364, name: "euro sign", category: "currency" },
  { entity: "&image;", character: "\u2111", codePoint: 8465, name: "black-letter capital I", category: "math" },
  { entity: "&weierp;", character: "\u2118", codePoint: 8472, name: "script capital P", category: "math" },
  { entity: "&real;", character: "\u211C", codePoint: 8476, name: "black-letter capital R", category: "math" },
  { entity: "&trade;", character: "\u2122", codePoint: 8482, name: "trade mark sign", category: "legal" },
  { entity: "&alefsym;", character: "\u2135", codePoint: 8501, name: "alef symbol", category: "math" },
  { entity: "&larr;", character: "\u2190", codePoint: 8592, name: "left arrow", category: "arrows" },
  { entity: "&uarr;", character: "\u2191", codePoint: 8593, name: "up arrow", category: "arrows" },
  { entity: "&rarr;", character: "\u2192", codePoint: 8594, name: "right arrow", category: "arrows" },
  { entity: "&darr;", character: "\u2193", codePoint: 8595, name: "down arrow", category: "arrows" },
  { entity: "&spades;", character: "\u2660", codePoint: 9824, name: "black spade suit", category: "symbols" },
  { entity: "&clubs;", character: "\u2663", codePoint: 9827, name: "black club suit", category: "symbols" },
  { entity: "&hearts;", character: "\u2665", codePoint: 9829, name: "black heart suit", category: "symbols" },
  { entity: "&diams;", character: "\u2666", codePoint: 9830, name: "black diamond suit", category: "symbols" },
];
