export interface HtmlEntity {
  entity: string;
  character: string;
  codePoint: number;
  name: string;
  category: string;
}

export const HTML_ENTITIES: HtmlEntity[] = [
  // Basic punctuation
  { entity: "&quot;", character: "\"", codePoint: 34, name: "quotation mark", category: "punctuation" },
  { entity: "&amp;", character: "&", codePoint: 38, name: "ampersand", category: "punctuation" },
  { entity: "&apos;", character: "'", codePoint: 39, name: "apostrophe", category: "punctuation" },
  { entity: "&lt;", character: "<", codePoint: 60, name: "less-than", category: "punctuation" },
  { entity: "&gt;", character: ">", codePoint: 62, name: "greater-than", category: "punctuation" },
  { entity: "&nbsp;", character: " ", codePoint: 160, name: "non-breaking space", category: "punctuation" },
  { entity: "&iexcl;", character: "¡", codePoint: 161, name: "inverted exclamation mark", category: "punctuation" },
  { entity: "&cent;", character: "¢", codePoint: 162, name: "cent sign", category: "currency" },
  { entity: "&pound;", character: "£", codePoint: 163, name: "pound sign", category: "currency" },
  { entity: "&curren;", character: "¤", codePoint: 164, name: "currency sign", category: "currency" },
  { entity: "&yen;", character: "¥", codePoint: 165, name: "yen sign", category: "currency" },
  { entity: "&brvbar;", character: "¦", codePoint: 166, name: "broken bar", category: "punctuation" },
  { entity: "&sect;", character: "§", codePoint: 167, name: "section sign", category: "punctuation" },
  { entity: "&uml;", character: "¨", codePoint: 168, name: "diaeresis", category: "diacritical" },
  { entity: "&copy;", character: "©", codePoint: 169, name: "copyright sign", category: "legal" },
  { entity: "&ordf;", character: "ª", codePoint: 170, name: "feminine ordinal indicator", category: "punctuation" },
  { entity: "&laquo;", character: "«", codePoint: 171, name: "left-pointing double angle quotation mark", category: "quotes" },
  { entity: "&not;", character: "¬", codePoint: 172, name: "not sign", category: "math" },
  { entity: "&shy;", character: "­", codePoint: 173, name: "soft hyphen", category: "punctuation" },
  { entity: "&reg;", character: "®", codePoint: 174, name: "registered sign", category: "legal" },
  { entity: "&macr;", character: "¯", codePoint: 175, name: "macron", category: "diacritical" },
  { entity: "&deg;", character: "°", codePoint: 176, name: "degree sign", category: "math" },
  { entity: "&plusmn;", character: "±", codePoint: 177, name: "plus-minus sign", category: "math" },
  { entity: "&sup2;", character: "²", codePoint: 178, name: "superscript two", category: "math" },
  { entity: "&sup3;", character: "³", codePoint: 179, name: "superscript three", category: "math" },
  { entity: "&acute;", character: "´", codePoint: 180, name: "acute accent", category: "diacritical" },
  { entity: "&micro;", character: "µ", codePoint: 181, name: "micro sign", category: "math" },
  { entity: "&para;", character: "¶", codePoint: 182, name: "pilcrow sign", category: "punctuation" },
  { entity: "&middot;", character: "·", codePoint: 183, name: "middle dot", category: "punctuation" },
  { entity: "&cedil;", character: "¸", codePoint: 184, name: "cedilla", category: "diacritical" },
  { entity: "&sup1;", character: "¹", codePoint: 185, name: "superscript one", category: "math" },
  { entity: "&ordm;", character: "º", codePoint: 186, name: "masculine ordinal indicator", category: "punctuation" },
  { entity: "&raquo;", character: "»", codePoint: 187, name: "right-pointing double angle quotation mark", category: "quotes" },
  { entity: "&frac14;", character: "¼", codePoint: 188, name: "vulgar fraction one quarter", category: "math" },
  { entity: "&frac12;", character: "½", codePoint: 189, name: "vulgar fraction one half", category: "math" },
  { entity: "&frac34;", character: "¾", codePoint: 190, name: "vulgar fraction three quarters", category: "math" },
  { entity: "&iquest;", character: "¿", codePoint: 191, name: "inverted question mark", category: "punctuation" },
  // Latin letters
  { entity: "&Agrave;", character: "À", codePoint: 192, name: "Latin capital letter A with grave", category: "latin" },
  { entity: "&Aacute;", character: "Á", codePoint: 193, name: "Latin capital letter A with acute", category: "latin" },
  { entity: "&Acirc;", character: "Â", codePoint: 194, name: "Latin capital letter A with circumflex", category: "latin" },
  { entity: "&Atilde;", character: "Ã", codePoint: 195, name: "Latin capital letter A with tilde", category: "latin" },
  { entity: "&Auml;", character: "Ä", codePoint: 196, name: "Latin capital letter A with diaeresis", category: "latin" },
  { entity: "&Aring;", character: "Å", codePoint: 197, name: "Latin capital letter A with ring above", category: "latin" },
  { entity: "&AElig;", character: "Æ", codePoint: 198, name: "Latin capital letter AE", category: "latin" },
  { entity: "&Ccedil;", character: "Ç", codePoint: 199, name: "Latin capital letter C with cedilla", category: "latin" },
  { entity: "&Egrave;", character: "È", codePoint: 200, name: "Latin capital letter E with grave", category: "latin" },
  { entity: "&Eacute;", character: "É", codePoint: 201, name: "Latin capital letter E with acute", category: "latin" },
  { entity: "&Ecirc;", character: "Ê", codePoint: 202, name: "Latin capital letter E with circumflex", category: "latin" },
  { entity: "&Euml;", character: "Ë", codePoint: 203, name: "Latin capital letter E with diaeresis", category: "latin" },
  { entity: "&Igrave;", character: "Ì", codePoint: 204, name: "Latin capital letter I with grave", category: "latin" },
  { entity: "&Iacute;", character: "Í", codePoint: 205, name: "Latin capital letter I with acute", category: "latin" },
  { entity: "&Icirc;", character: "Î", codePoint: 206, name: "Latin capital letter I with circumflex", category: "latin" },
  { entity: "&Iuml;", character: "Ï", codePoint: 207, name: "Latin capital letter I with diaeresis", category: "latin" },
  { entity: "&ETH;", character: "Ð", codePoint: 208, name: "Latin capital letter Eth", category: "latin" },
  { entity: "&Ntilde;", character: "Ñ", codePoint: 209, name: "Latin capital letter N with tilde", category: "latin" },
  { entity: "&Ograve;", character: "Ò", codePoint: 210, name: "Latin capital letter O with grave", category: "latin" },
  { entity: "&Oacute;", character: "Ó", codePoint: 211, name: "Latin capital letter O with acute", category: "latin" },
  { entity: "&Ocirc;", character: "Ô", codePoint: 212, name: "Latin capital letter O with circumflex", category: "latin" },
  { entity: "&Otilde;", character: "Õ", codePoint: 213, name: "Latin capital letter O with tilde", category: "latin" },
  { entity: "&Ouml;", character: "Ö", codePoint: 214, name: "Latin capital letter O with diaeresis", category: "latin" },
  { entity: "&times;", character: "×", codePoint: 215, name: "multiplication sign", category: "math" },
  { entity: "&Oslash;", character: "Ø", codePoint: 216, name: "Latin capital letter O with stroke", category: "latin" },
  { entity: "&Ugrave;", character: "Ù", codePoint: 217, name: "Latin capital letter U with grave", category: "latin" },
  { entity: "&Uacute;", character: "Ú", codePoint: 218, name: "Latin capital letter U with acute", category: "latin" },
  { entity: "&Ucirc;", character: "Û", codePoint: 219, name: "Latin capital letter U with circumflex", category: "latin" },
  { entity: "&Uuml;", character: "Ü", codePoint: 220, name: "Latin capital letter U with diaeresis", category: "latin" },
  { entity: "&Yacute;", character: "Ý", codePoint: 221, name: "Latin capital letter Y with acute", category: "latin" },
  { entity: "&THORN;", character: "Þ", codePoint: 222, name: "Latin capital letter Thorn", category: "latin" },
  { entity: "&szlig;", character: "ß", codePoint: 223, name: "Latin small letter sharp s", category: "latin" },
  { entity: "&agrave;", character: "à", codePoint: 224, name: "Latin small letter a with grave", category: "latin" },
  { entity: "&aacute;", character: "á", codePoint: 225, name: "Latin small letter a with acute", category: "latin" },
  { entity: "&acirc;", character: "â", codePoint: 226, name: "Latin small letter a with circumflex", category: "latin" },
  { entity: "&atilde;", character: "ã", codePoint: 227, name: "Latin small letter a with tilde", category: "latin" },
  { entity: "&auml;", character: "ä", codePoint: 228, name: "Latin small letter a with diaeresis", category: "latin" },
  { entity: "&aring;", character: "å", codePoint: 229, name: "Latin small letter a with ring above", category: "latin" },
  { entity: "&aelig;", character: "æ", codePoint: 230, name: "Latin small letter ae", category: "latin" },
  { entity: "&ccedil;", character: "ç", codePoint: 231, name: "Latin small letter c with cedilla", category: "latin" },
  { entity: "&egrave;", character: "è", codePoint: 232, name: "Latin small letter e with grave", category: "latin" },
  { entity: "&eacute;", character: "é", codePoint: 233, name: "Latin small letter e with acute", category: "latin" },
  { entity: "&ecirc;", character: "ê", codePoint: 234, name: "Latin small letter e with circumflex", category: "latin" },
  { entity: "&euml;", character: "ë", codePoint: 235, name: "Latin small letter e with diaeresis", category: "latin" },
  { entity: "&igrave;", character: "ì", codePoint: 236, name: "Latin small letter i with grave", category: "latin" },
  { entity: "&iacute;", character: "í", codePoint: 237, name: "Latin small letter i with acute", category: "latin" },
  { entity: "&icirc;", character: "î", codePoint: 238, name: "Latin small letter i with circumflex", category: "latin" },
  { entity: "&iuml;", character: "ï", codePoint: 239, name: "Latin small letter i with diaeresis", category: "latin" },
  { entity: "&eth;", character: "ð", codePoint: 240, name: "Latin small letter eth", category: "latin" },
  { entity: "&ntilde;", character: "ñ", codePoint: 241, name: "Latin small letter n with tilde", category: "latin" },
  { entity: "&ograve;", character: "ò", codePoint: 242, name: "Latin small letter o with grave", category: "latin" },
  { entity: "&oacute;", character: "ó", codePoint: 243, name: "Latin small letter o with acute", category: "latin" },
  { entity: "&ocirc;", character: "ô", codePoint: 244, name: "Latin small letter o with circumflex", category: "latin" },
  { entity: "&otilde;", character: "õ", codePoint: 245, name: "Latin small letter o with tilde", category: "latin" },
  { entity: "&ouml;", character: "ö", codePoint: 246, name: "Latin small letter o with diaeresis", category: "latin" },
  { entity: "&divide;", character: "÷", codePoint: 247, name: "division sign", category: "math" },
  { entity: "&oslash;", character: "ø", codePoint: 248, name: "Latin small letter o with stroke", category: "latin" },
  { entity: "&ugrave;", character: "ù", codePoint: 249, name: "Latin small letter u with grave", category: "latin" },
  { entity: "&uacute;", character: "ú", codePoint: 250, name: "Latin small letter u with acute", category: "latin" },
  { entity: "&ucirc;", character: "û", codePoint: 251, name: "Latin small letter u with circumflex", category: "latin" },
  { entity: "&uuml;", character: "ü", codePoint: 252, name: "Latin small letter u with diaeresis", category: "latin" },
  { entity: "&yacute;", character: "ý", codePoint: 253, name: "Latin small letter y with acute", category: "latin" },
  { entity: "&thorn;", character: "þ", codePoint: 254, name: "Latin small letter thorn", category: "latin" },
  { entity: "&yuml;", character: "ÿ", codePoint: 255, name: "Latin small letter y with diaeresis", category: "latin" },
  // Greek letters
  { entity: "&Alpha;", character: "Α", codePoint: 913, name: "Greek capital letter Alpha", category: "greek" },
  { entity: "&Beta;", character: "Β", codePoint: 914, name: "Greek capital letter Beta", category: "greek" },
  { entity: "&Gamma;", character: "Γ", codePoint: 915, name: "Greek capital letter Gamma", category: "greek" },
  { entity: "&Delta;", character: "Δ", codePoint: 916, name: "Greek capital letter Delta", category: "greek" },
  { entity: "&Epsilon;", character: "Ε", codePoint: 917, name: "Greek capital letter Epsilon", category: "greek" },
  { entity: "&Zeta;", character: "Ζ", codePoint: 918, name: "Greek capital letter Zeta", category: "greek" },
  { entity: "&Eta;", character: "Η", codePoint: 919, name: "Greek capital letter Eta", category: "greek" },
  { entity: "&Theta;", character: "Θ", codePoint: 920, name: "Greek capital letter Theta", category: "greek" },
  { entity: "&Iota;", character: "Ι", codePoint: 921, name: "Greek capital letter Iota", category: "greek" },
  { entity: "&Kappa;", character: "Κ", codePoint: 922, name: "Greek capital letter Kappa", category: "greek" },
  { entity: "&Lambda;", character: "Λ", codePoint: 923, name: "Greek capital letter Lambda", category: "greek" },
  { entity: "&Mu;", character: "Μ", codePoint: 924, name: "Greek capital letter Mu", category: "greek" },
  { entity: "&Nu;", character: "Ν", codePoint: 925, name: "Greek capital letter Nu", category: "greek" },
  { entity: "&Xi;", character: "Ξ", codePoint: 926, name: "Greek capital letter Xi", category: "greek" },
  { entity: "&Omicron;", character: "Ο", codePoint: 927, name: "Greek capital letter Omicron", category: "greek" },
  { entity: "&Pi;", character: "Π", codePoint: 928, name: "Greek capital letter Pi", category: "greek" },
  { entity: "&Rho;", character: "Ρ", codePoint: 929, name: "Greek capital letter Rho", category: "greek" },
  { entity: "&Sigma;", character: "Σ", codePoint: 931, name: "Greek capital letter Sigma", category: "greek" },
  { entity: "&Tau;", character: "Τ", codePoint: 932, name: "Greek capital letter Tau", category: "greek" },
  { entity: "&Upsilon;", character: "Υ", codePoint: 933, name: "Greek capital letter Upsilon", category: "greek" },
  { entity: "&Phi;", character: "Φ", codePoint: 934, name: "Greek capital letter Phi", category: "greek" },
  { entity: "&Chi;", character: "Χ", codePoint: 935, name: "Greek capital letter Chi", category: "greek" },
  { entity: "&Psi;", character: "Ψ", codePoint: 936, name: "Greek capital letter Psi", category: "greek" },
  { entity: "&Omega;", character: "Ω", codePoint: 937, name: "Greek capital letter Omega", category: "greek" },
  { entity: "&alpha;", character: "α", codePoint: 945, name: "Greek small letter alpha", category: "greek" },
  { entity: "&beta;", character: "β", codePoint: 946, name: "Greek small letter beta", category: "greek" },
  { entity: "&gamma;", character: "γ", codePoint: 947, name: "Greek small letter gamma", category: "greek" },
  { entity: "&delta;", character: "δ", codePoint: 948, name: "Greek small letter delta", category: "greek" },
  { entity: "&epsilon;", character: "ε", codePoint: 949, name: "Greek small letter epsilon", category: "greek" },
  { entity: "&zeta;", character: "ζ", codePoint: 950, name: "Greek small letter zeta", category: "greek" },
  { entity: "&eta;", character: "η", codePoint: 951, name: "Greek small letter eta", category: "greek" },
  { entity: "&theta;", character: "θ", codePoint: 952, name: "Greek small letter theta", category: "greek" },
  { entity: "&iota;", character: "ι", codePoint: 953, name: "Greek small letter iota", category: "greek" },
  { entity: "&kappa;", character: "κ", codePoint: 954, name: "Greek small letter kappa", category: "greek" },
  { entity: "&lambda;", character: "λ", codePoint: 955, name: "Greek small letter lambda", category: "greek" },
  { entity: "&mu;", character: "μ", codePoint: 956, name: "Greek small letter mu", category: "greek" },
  { entity: "&nu;", character: "ν", codePoint: 957, name: "Greek small letter nu", category: "greek" },
  { entity: "&xi;", character: "ξ", codePoint: 958, name: "Greek small letter xi", category: "greek" },
  { entity: "&omicron;", character: "ο", codePoint: 959, name: "Greek small letter omicron", category: "greek" },
  { entity: "&pi;", character: "π", codePoint: 960, name: "Greek small letter pi", category: "greek" },
  { entity: "&rho;", character: "ρ", codePoint: 961, name: "Greek small letter rho", category: "greek" },
  { entity: "&sigmaf;", character: "ς", codePoint: 962, name: "Greek small letter final sigma", category: "greek" },
  { entity: "&sigma;", character: "σ", codePoint: 963, name: "Greek small letter sigma", category: "greek" },
  { entity: "&tau;", character: "τ", codePoint: 964, name: "Greek small letter tau", category: "greek" },
  { entity: "&upsilon;", character: "υ", codePoint: 965, name: "Greek small letter upsilon", category: "greek" },
  { entity: "&phi;", character: "φ", codePoint: 966, name: "Greek small letter phi", category: "greek" },
  { entity: "&chi;", character: "χ", codePoint: 967, name: "Greek small letter chi", category: "greek" },
  { entity: "&psi;", character: "ψ", codePoint: 968, name: "Greek small letter psi", category: "greek" },
  { entity: "&omega;", character: "ω", codePoint: 969, name: "Greek small letter omega", category: "greek" },
  // Math symbols
  { entity: "&forall;", character: "∀", codePoint: 8704, name: "for all", category: "math" },
  { entity: "&part;", character: "∂", codePoint: 8706, name: "partial differential", category: "math" },
  { entity: "&exist;", character: "∃", codePoint: 8707, name: "there exists", category: "math" },
  { entity: "&empty;", character: "∅", codePoint: 8709, name: "empty set", category: "math" },
  { entity: "&nabla;", character: "∇", codePoint: 8711, name: "nabla", category: "math" },
  { entity: "&isin;", character: "∈", codePoint: 8712, name: "element of", category: "math" },
  { entity: "&notin;", character: "∉", codePoint: 8713, name: "not an element of", category: "math" },
  { entity: "&ni;", character: "∋", codePoint: 8715, name: "contains as member", category: "math" },
  { entity: "&prod;", character: "∏", codePoint: 8719, name: "n-ary product", category: "math" },
  { entity: "&sum;", character: "∑", codePoint: 8721, name: "n-ary summation", category: "math" },
  { entity: "&minus;", character: "−", codePoint: 8722, name: "minus sign", category: "math" },
  { entity: "&lowast;", character: "∗", codePoint: 8727, name: "asterisk operator", category: "math" },
  { entity: "&radic;", character: "√", codePoint: 8730, name: "square root", category: "math" },
  { entity: "&prop;", character: "∝", codePoint: 8733, name: "proportional to", category: "math" },
  { entity: "&infin;", character: "∞", codePoint: 8734, name: "infinity", category: "math" },
  { entity: "&ang;", character: "∠", codePoint: 8736, name: "angle", category: "math" },
  { entity: "&and;", character: "∧", codePoint: 8743, name: "logical and", category: "math" },
  { entity: "&or;", character: "∨", codePoint: 8744, name: "logical or", category: "math" },
  { entity: "&cap;", character: "∩", codePoint: 8745, name: "intersection", category: "math" },
  { entity: "&cup;", character: "∪", codePoint: 8746, name: "union", category: "math" },
  { entity: "&int;", character: "∫", codePoint: 8747, name: "integral", category: "math" },
  { entity: "&there4;", character: "∴", codePoint: 8756, name: "therefore", category: "math" },
  { entity: "&sim;", character: "∼", codePoint: 8764, name: "tilde operator", category: "math" },
  { entity: "&cong;", character: "≅", codePoint: 8773, name: "approximately equal to", category: "math" },
  { entity: "&asymp;", character: "≈", codePoint: 8776, name: "almost equal to", category: "math" },
  { entity: "&ne;", character: "≠", codePoint: 8800, name: "not equal to", category: "math" },
  { entity: "&equiv;", character: "≡", codePoint: 8801, name: "identical to", category: "math" },
  { entity: "&le;", character: "≤", codePoint: 8804, name: "less-than or equal to", category: "math" },
  { entity: "&ge;", character: "≥", codePoint: 8805, name: "greater-than or equal to", category: "math" },
  { entity: "&sub;", character: "⊂", codePoint: 8834, name: "subset of", category: "math" },
  { entity: "&sup;", character: "⊃", codePoint: 8835, name: "superset of", category: "math" },
  { entity: "&nsub;", character: "⊄", codePoint: 8836, name: "not a subset of", category: "math" },
  { entity: "&sube;", character: "⊆", codePoint: 8838, name: "subset of or equal to", category: "math" },
  { entity: "&supe;", character: "⊇", codePoint: 8839, name: "superset of or equal to", category: "math" },
  { entity: "&oplus;", character: "⊕", codePoint: 8853, name: "circled plus", category: "math" },
  { entity: "&otimes;", character: "⊗", codePoint: 8855, name: "circled times", category: "math" },
  { entity: "&perp;", character: "⊥", codePoint: 8869, name: "up tack", category: "math" },
  { entity: "&sdot;", character: "⋅", codePoint: 8901, name: "dot operator", category: "math" },
  // Arrows
  { entity: "&larr;", character: "←", codePoint: 8592, name: "leftwards arrow", category: "arrows" },
  { entity: "&uarr;", character: "↑", codePoint: 8593, name: "upwards arrow", category: "arrows" },
  { entity: "&rarr;", character: "→", codePoint: 8594, name: "rightwards arrow", category: "arrows" },
  { entity: "&darr;", character: "↓", codePoint: 8595, name: "downwards arrow", category: "arrows" },
  { entity: "&harr;", character: "↔", codePoint: 8596, name: "left right arrow", category: "arrows" },
  { entity: "&crarr;", character: "↵", codePoint: 8629, name: "downwards arrow with corner leftwards", category: "arrows" },
  { entity: "&lArr;", character: "⇐", codePoint: 8656, name: "leftwards double arrow", category: "arrows" },
  { entity: "&uArr;", character: "⇑", codePoint: 8657, name: "upwards double arrow", category: "arrows" },
  { entity: "&rArr;", character: "⇒", codePoint: 8658, name: "rightwards double arrow", category: "arrows" },
  { entity: "&dArr;", character: "⇓", codePoint: 8659, name: "downwards double arrow", category: "arrows" },
  { entity: "&hArr;", character: "⇔", codePoint: 8660, name: "left right double arrow", category: "arrows" },
  // Special characters
  { entity: "&bull;", character: "•", codePoint: 8226, name: "bullet", category: "punctuation" },
  { entity: "&hellip;", character: "…", codePoint: 8230, name: "horizontal ellipsis", category: "punctuation" },
  { entity: "&prime;", character: "′", codePoint: 8242, name: "prime", category: "math" },
  { entity: "&Prime;", character: "″", codePoint: 8243, name: "double prime", category: "math" },
  { entity: "&lsaquo;", character: "‹", codePoint: 8249, name: "single left-pointing angle quotation mark", category: "quotes" },
  { entity: "&rsaquo;", character: "›", codePoint: 8250, name: "single right-pointing angle quotation mark", category: "quotes" },
  { entity: "&oline;", character: "‾", codePoint: 8254, name: "overline", category: "punctuation" },
  { entity: "&frasl;", character: "⁄", codePoint: 8260, name: "fraction slash", category: "math" },
  { entity: "&euro;", character: "€", codePoint: 8364, name: "euro sign", category: "currency" },
  { entity: "&image;", character: "ℑ", codePoint: 8465, name: "black-letter capital I", category: "math" },
  { entity: "&weierp;", character: "℘", codePoint: 8472, name: "script capital P", category: "math" },
  { entity: "&real;", character: "ℜ", codePoint: 8476, name: "black-letter capital R", category: "math" },
  { entity: "&trade;", character: "™", codePoint: 8482, name: "trade mark sign", category: "legal" },
  { entity: "&alefsym;", character: "ℵ", codePoint: 8501, name: "alef symbol", category: "math" },
  { entity: "&larr;", character: "←", codePoint: 8592, name: "left arrow", category: "arrows" },
  { entity: "&uarr;", character: "↑", codePoint: 8593, name: "up arrow", category: "arrows" },
  { entity: "&rarr;", character: "→", codePoint: 8594, name: "right arrow", category: "arrows" },
  { entity: "&darr;", character: "↓", codePoint: 8595, name: "down arrow", category: "arrows" },
  { entity: "&spades;", character: "♠", codePoint: 9824, name: "black spade suit", category: "symbols" },
  { entity: "&clubs;", character: "♣", codePoint: 9827, name: "black club suit", category: "symbols" },
  { entity: "&hearts;", character: "♥", codePoint: 9829, name: "black heart suit", category: "symbols" },
  { entity: "&diams;", character: "♦", codePoint: 9830, name: "black diamond suit", category: "symbols" },
];
