export interface MimeType {
  extension: string;
  mime: string;
  category: string;
  description: string;
}

export const MIME_TYPES: MimeType[] = [
  // Text
  { extension: "html", mime: "text/html", category: "text", description: "HTML document" },
  { extension: "htm", mime: "text/html", category: "text", description: "HTML document" },
  { extension: "css", mime: "text/css", category: "text", description: "Cascading Style Sheets" },
  { extension: "csv", mime: "text/csv", category: "text", description: "Comma-separated values" },
  { extension: "txt", mime: "text/plain", category: "text", description: "Plain text" },
  { extension: "xml", mime: "application/xml", category: "text", description: "XML document" },
  { extension: "js", mime: "text/javascript", category: "text", description: "JavaScript" },
  { extension: "mjs", mime: "text/javascript", category: "text", description: "ES Module JavaScript" },
  { extension: "md", mime: "text/markdown", category: "text", description: "Markdown document" },
  { extension: "rtf", mime: "text/rtf", category: "text", description: "Rich Text Format" },
  // Image
  { extension: "jpg", mime: "image/jpeg", category: "image", description: "JPEG image" },
  { extension: "jpeg", mime: "image/jpeg", category: "image", description: "JPEG image" },
  { extension: "png", mime: "image/png", category: "image", description: "PNG image" },
  { extension: "gif", mime: "image/gif", category: "image", description: "GIF image" },
  { extension: "webp", mime: "image/webp", category: "image", description: "WebP image" },
  { extension: "svg", mime: "image/svg+xml", category: "image", description: "SVG vector image" },
  { extension: "ico", mime: "image/x-icon", category: "image", description: "Favicon" },
  { extension: "bmp", mime: "image/bmp", category: "image", description: "Bitmap image" },
  { extension: "tiff", mime: "image/tiff", category: "image", description: "TIFF image" },
  { extension: "tif", mime: "image/tiff", category: "image", description: "TIFF image" },
  { extension: "avif", mime: "image/avif", category: "image", description: "AVIF image" },
  { extension: "heic", mime: "image/heic", category: "image", description: "HEIC image" },
  { extension: "heif", mime: "image/heif", category: "image", description: "HEIF image" },
  // Audio
  { extension: "mp3", mime: "audio/mpeg", category: "audio", description: "MP3 audio" },
  { extension: "wav", mime: "audio/wav", category: "audio", description: "WAV audio" },
  { extension: "ogg", mime: "audio/ogg", category: "audio", description: "OGG audio" },
  { extension: "m4a", mime: "audio/mp4", category: "audio", description: "MP4 audio" },
  { extension: "flac", mime: "audio/flac", category: "audio", description: "FLAC audio" },
  { extension: "aac", mime: "audio/aac", category: "audio", description: "AAC audio" },
  { extension: "wma", mime: "audio/x-ms-wma", category: "audio", description: "Windows Media Audio" },
  { extension: "opus", mime: "audio/opus", category: "audio", description: "Opus audio" },
  { extension: "mid", mime: "audio/midi", category: "audio", description: "MIDI audio" },
  { extension: "midi", mime: "audio/midi", category: "audio", description: "MIDI audio" },
  // Video
  { extension: "mp4", mime: "video/mp4", category: "video", description: "MP4 video" },
  { extension: "m4v", mime: "video/mp4", category: "video", description: "MP4 video" },
  { extension: "webm", mime: "video/webm", category: "video", description: "WebM video" },
  { extension: "avi", mime: "video/x-msvideo", category: "video", description: "AVI video" },
  { extension: "mov", mime: "video/quicktime", category: "video", description: "QuickTime video" },
  { extension: "wmv", mime: "video/x-ms-wmv", category: "video", description: "Windows Media Video" },
  { extension: "flv", mime: "video/x-flv", category: "video", description: "Flash video" },
  { extension: "mkv", mime: "video/x-matroska", category: "video", description: "Matroska video" },
  { extension: "mpeg", mime: "video/mpeg", category: "video", description: "MPEG video" },
  { extension: "mpg", mime: "video/mpeg", category: "video", description: "MPEG video" },
  { extension: "3gp", mime: "video/3gpp", category: "video", description: "3GPP mobile video" },
  // Application
  { extension: "pdf", mime: "application/pdf", category: "application", description: "PDF document" },
  { extension: "json", mime: "application/json", category: "application", description: "JSON data" },
  { extension: "zip", mime: "application/zip", category: "application", description: "ZIP archive" },
  { extension: "gz", mime: "application/gzip", category: "application", description: "GZip compressed archive" },
  { extension: "tar", mime: "application/x-tar", category: "application", description: "Tar archive" },
  { extension: "rar", mime: "application/vnd.rar", category: "application", description: "RAR archive" },
  { extension: "7z", mime: "application/x-7z-compressed", category: "application", description: "7-Zip archive" },
  { extension: "exe", mime: "application/vnd.microsoft.portable-executable", category: "application", description: "Windows executable" },
  { extension: "dll", mime: "application/x-msdownload", category: "application", description: "Windows DLL" },
  { extension: "doc", mime: "application/msword", category: "application", description: "Microsoft Word document" },
  { extension: "docx", mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", category: "application", description: "Microsoft Word OpenXML document" },
  { extension: "xls", mime: "application/vnd.ms-excel", category: "application", description: "Microsoft Excel spreadsheet" },
  { extension: "xlsx", mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", category: "application", description: "Microsoft Excel OpenXML spreadsheet" },
  { extension: "ppt", mime: "application/vnd.ms-powerpoint", category: "application", description: "Microsoft PowerPoint presentation" },
  { extension: "pptx", mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation", category: "application", description: "Microsoft PowerPoint OpenXML presentation" },
  { extension: "wasm", mime: "application/wasm", category: "application", description: "WebAssembly binary" },
  { extension: "woff", mime: "font/woff", category: "font", description: "Web Open Font Format" },
  { extension: "woff2", mime: "font/woff2", category: "font", description: "Web Open Font Format 2" },
  { extension: "ttf", mime: "font/ttf", category: "font", description: "TrueType font" },
  { extension: "otf", mime: "font/otf", category: "font", description: "OpenType font" },
  { extension: "eot", mime: "application/vnd.ms-fontobject", category: "font", description: "Embedded OpenType font" },
  { extension: "wasm", mime: "application/wasm", category: "application", description: "WebAssembly" },
  { extension: "bin", mime: "application/octet-stream", category: "application", description: "Binary data" },
  { extension: "yaml", mime: "text/yaml", category: "text", description: "YAML document" },
  { extension: "yml", mime: "text/yaml", category: "text", description: "YAML document" },
  { extension: "toml", mime: "application/toml", category: "application", description: "TOML configuration" },
  { extension: "ini", mime: "text/plain", category: "text", description: "INI configuration" },
  { extension: "cfg", mime: "text/plain", category: "text", description: "Configuration file" },
  { extension: "log", mime: "text/plain", category: "text", description: "Log file" },
  { extension: "sql", mime: "text/plain", category: "text", description: "SQL script" },
  { extension: "sh", mime: "text/x-shellscript", category: "text", description: "Shell script" },
  { extension: "bat", mime: "text/x-bat", category: "text", description: "Windows batch file" },
  { extension: "ps1", mime: "text/x-powershell", category: "text", description: "PowerShell script" },
];
