import type { Metadata } from "next";
import { CssGradientGenerator } from "@/components/css-gradient-generator/css-gradient-generator";
import {
  ToolLayout,
  ToolHero,
  FaqSection,
  RelatedTools,
  RelatedContent,
  JsonLd,
} from "@/components/shared";
import {
  faqSchema,
  webPageSchema,
  breadcrumbSchema,
  softwareAppSchema,
  type FaqItem,
} from "@/lib/seo";
import { SITE_URL } from "@/lib/constants";
import Link from "next/link";

const slug = "css-gradient-generator";
const pageTitle = "CSS Gradient Generator - Create Beautiful Gradients Online";
const pageDescription =
  "Create stunning CSS gradients with a visual editor. Choose linear or radial gradients, customize color stops, preview live, and copy the generated CSS code instantly.";

export const metadata: Metadata = {
  title: pageTitle,
  description: pageDescription,
  openGraph: {
    title: pageTitle,
    description: pageDescription,
    url: `${SITE_URL}/${slug}`,
  },
  twitter: {
    title: pageTitle,
    description: pageDescription,
  },
  alternates: {
    canonical: `${SITE_URL}/${slug}`,
  },
};

const breadcrumbs = [
  { label: "Home", href: SITE_URL },
  { label: "Image & Design", href: `${SITE_URL}/category/image-design` },
  { label: "CSS Gradient Generator" },
];

const faqItems: FaqItem[] = [
  {
    question: "What types of CSS gradients can I create?",
    answer:
      "The generator supports both linear gradients (colors transition along a straight line) and radial gradients (colors radiate from a central point). For linear gradients, you can choose from directions like to right, to bottom, and diagonal angles. For radial gradients, you can choose between circle and ellipse shapes. Each type supports 2 to 5 color stops at customizable positions.",
  },
  {
    question: "How do I use the generated CSS gradient code?",
    answer:
      "Copy the generated CSS code using the Copy button and paste it into your stylesheet. The code uses the standard background CSS property with the linear-gradient or radial-gradient function. You can apply it to any HTML element by using a class, ID, or inline styles. The generated code is browser-compatible and ready for production use.",
  },
  {
    question: "What is a color stop in CSS gradients?",
    answer:
      "A color stop is a specific color value at a specific position along the gradient line or radius. By placing multiple color stops at different positions, you control exactly how the gradient transitions. For example, red at 0% and blue at 100% creates a smooth red-to-blue transition. Adding a third stop at 50% creates a two-stage transition through the intermediate color.",
  },
  {
    question: "Can I create multi-color gradients with more than two colors?",
    answer:
      "Yes. You can add up to 5 color stops to create complex multi-color gradients. Each stop has its own color picker and position slider. Adding intermediate colors creates richer visual effects, such as sunset gradients (red to orange to yellow) or brand gradients that transition through multiple brand colors.",
  },
  {
    question: "What is the difference between linear and radial gradients?",
    answer:
      "Linear gradients transition colors along a straight line in a specified direction. Radial gradients transition colors outward from a central point in a circular or elliptical shape. Linear gradients are best for backgrounds, buttons, and headers. Radial gradients work well for spotlight effects, badges, call-to-action elements, and subtle lighting simulations.",
  },
  {
    question: "How does the gradient direction affect the result?",
    answer:
      "The direction determines the angle of color transition. To right creates a horizontal gradient from left to right. To bottom creates a vertical gradient from top to bottom. Diagonal directions (to bottom right, to top right) create angled transitions. For radial gradients, the choice between circle and ellipse determines whether the gradient maintains a perfect circle or stretches to fill the element's aspect ratio.",
  },
  {
    question: "Is the CSS gradient compatible with all browsers?",
    answer:
      "The CSS gradient syntax generated by this tool uses the standard syntax supported by all modern browsers including Chrome, Firefox, Safari, and Edge. The linear-gradient and radial-gradient functions have been widely supported since 2013. For very old browsers, consider adding a solid background-color fallback before the gradient declaration.",
  },
  {
    question: "Can I use gradients with Tailwind CSS or other frameworks?",
    answer:
      "Yes. You can use the generated gradient code directly in Tailwind CSS by adding custom styles to your tailwind.config.js under the extend.theme.extend.backgroundImage section, or use inline styles with the style attribute. The generated code is pure CSS and works with any framework including React, Vue, Angular, and plain HTML/CSS projects.",
  },
];

export default function CssGradientGeneratorPage() {
  return (
    <>
      <JsonLd data={webPageSchema({ name: pageTitle, description: pageDescription, url: `${SITE_URL}/${slug}`, breadcrumbs })} />
      <JsonLd data={breadcrumbSchema(breadcrumbs)} />
      <JsonLd data={faqSchema(faqItems)} />
      <JsonLd data={softwareAppSchema({ name: pageTitle, description: pageDescription, url: `${SITE_URL}/${slug}` })} />

      <section className="border-b border-zinc-200 dark:border-zinc-800">
        <ToolLayout toolSlug={slug}>
          <ToolHero
            title="CSS Gradient Generator"
            description="Create beautiful, custom CSS gradients with an intuitive visual editor. Choose between linear and radial gradients, pick your colors, adjust stop positions, and get production-ready CSS code."
            breadcrumbs={breadcrumbs}
          >
            <CssGradientGenerator />
          </ToolHero>
        </ToolLayout>
      </section>

      <section className="border-b border-zinc-200 py-16 dark:border-zinc-800 sm:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <h2 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 sm:text-4xl">
            Why CSS Gradients Elevate Web Design
          </h2>
          <div className="mt-8 space-y-4 text-zinc-600 dark:text-zinc-400">
            <p>
              CSS gradients have transformed web design by enabling rich, visually appealing backgrounds without the performance cost of images. A gradient is pure CSS — no HTTP requests, no file sizes, no loading delays. Browsers render gradients natively, often using GPU acceleration for smooth animations and transitions. This makes gradients ideal for hero sections, button hover effects, card backgrounds, and full-page layouts where image files would add unnecessary bloat and complexity.
            </p>
            <p>
              Beyond aesthetics, gradients serve functional purposes in UI design. They create depth and hierarchy by suggesting light sources and elevation. A subtle gradient on a button makes it appear raised and clickable. A gradient overlay on a hero image improves text readability by providing contrast where the image alone may be insufficient. For color-conscious designs, starting with a strong gradient palette and pairing it with the <Link href="/color-converter" className="text-blue-600 hover:underline dark:text-blue-400">Color Converter</Link> ensures your color values are consistent across HEX, RGB, and HSL formats used in your project.
            </p>
          </div>
        </div>
      </section>

      <section className="border-b border-zinc-200 py-16 dark:border-zinc-800 sm:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <h2 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 sm:text-4xl">
            Best Practices for Using CSS Gradients in Production
          </h2>
          <div className="mt-8 space-y-4 text-zinc-600 dark:text-zinc-400">
            <p>
              When using gradients in production, always provide a solid background-color fallback before the gradient declaration. Older browsers that do not support gradients will display the fallback color instead of a blank background. For accessibility, ensure sufficient contrast between text and gradient backgrounds. A semi-transparent overlay or text shadow can improve readability when text is placed over gradients with varying lightness levels.
            </p>
            <p>
              Performance considerations matter too. While gradients are efficient, animating gradient properties (like background-position) can trigger expensive repaints. For animated effects, prefer opacity transitions on gradient overlays or use pseudo-elements with transform animations. In design systems, define gradient tokens as CSS custom properties for consistency across components. This makes it easy to update the brand gradient in one place and have it propagate through your entire application. For color palette exploration alongside gradients, the <Link href="/color-converter" className="text-blue-600 hover:underline dark:text-blue-400">Color Converter</Link> helps match gradient colors with your broader design system.
            </p>
          </div>
        </div>
      </section>

      <section className="border-b border-zinc-200 py-16 dark:border-zinc-800 sm:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <FaqSection items={faqItems} title="Frequently Asked Questions About CSS Gradients" />
        </div>
      </section>

      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <RelatedTools
            tools={[
              { icon: "Palette", title: "Color Converter", description: "Convert colors between HEX, RGB, and HSL formats", href: "/color-converter" },
              { icon: "Smartphone", title: "QR Code Generator", description: "Generate QR codes from any text or URL", href: "/qr-code-generator" },
              { icon: "BarChart3", title: "Barcode Generator", description: "Generate barcodes in Code 128, EAN-13, and UPC-A", href: "/barcode-generator" },
              { icon: "Image", title: "Image Resizer", description: "Resize images online with aspect ratio lock", href: "/image-resizer" },
            ]}
            title="Related Design Tools"
          />
        </div>
      </section>
      <RelatedContent toolSlug="css-gradient-generator" />
    </>
  );
}
