"use client";

import { useState, useCallback, useMemo } from "react";
import { Button, Input } from "@/components/ui";

export function DmarcGenerator() {
  const [policy, setPolicy] = useState<"none" | "quarantine" | "reject">("none");
  const [rua, setRua] = useState("");
  const [ruf, setRuf] = useState("");
  const [pct, setPct] = useState("100");
  const [spPolicy, setSpPolicy] = useState<"none" | "quarantine" | "reject" | "">("");
  const [adkim, setAdkim] = useState<"s" | "r" | "">("");
  const [aspf, setAspf] = useState<"s" | "r" | "">("");
  const [fo, setFo] = useState<"0" | "1" | "d" | "s" | "">("");
  const [copied, setCopied] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [showGuide, setShowGuide] = useState(true);

  const tags: string[] = [`v=DMARC1`, `p=${policy}`];
  if (spPolicy) tags.push(`sp=${spPolicy}`);
  if (pct && pct !== "100") tags.push(`pct=${pct}`);
  if (rua) tags.push(`rua=mailto:${rua}`);
  if (ruf) tags.push(`ruf=mailto:${ruf}`);
  if (adkim) tags.push(`adkim=${adkim}`);
  if (aspf) tags.push(`aspf=${aspf}`);
  if (fo) tags.push(`fo=${fo}`);

  const record = tags.join("; ");

  const warnings = useMemo(() => {
    const w: { type: "warning" | "info"; text: string }[] = [];
    if (policy === "none" && !rua) w.push({ type: "warning", text: "p=none without rua means you have no visibility into your email authentication status." });
    if (rua && !rua.includes("@")) w.push({ type: "warning", text: "Report URI (rua) should be a valid email address." });
    if (policy === "reject" && pct !== "100") w.push({ type: "info", text: "p=reject with pct less than 100 means only a portion of email is rejected. Consider increasing pct gradually." });
    if (!rua) w.push({ type: "info", text: "Add an rua address to receive aggregate DMARC reports for monitoring." });
    return w;
  }, [policy, rua, pct]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(`${record};`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [record]);

  const handleDownloadTxt = useCallback(() => {
    const content = `; DMARC Record for your domain\n; Generated by Nuvora\n;\n_dmarc  IN  TXT  "${record};"`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "dmarc-record.txt";
    a.click();
    URL.revokeObjectURL(url);
  }, [record]);

  function resetForm() {
    setPolicy("none"); setRua(""); setRuf(""); setPct("100"); setSpPolicy("");
    setAdkim(""); setAspf(""); setFo(""); setCopied(false);
  }

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      {showGuide && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 px-5 py-4 dark:border-blue-800 dark:bg-blue-950">
          <div className="mb-2 flex items-center justify-between">
            <p className="text-xs font-semibold uppercase tracking-wider text-blue-700 dark:text-blue-300">DMARC Deployment Strategy (RFC 7489)</p>
            <button type="button" onClick={() => setShowGuide(false)} className="text-xs text-blue-700 hover:text-blue-700">Dismiss</button>
          </div>
          <ol className="ml-4 list-decimal space-y-1 text-sm text-blue-800 dark:text-blue-200">
            <li><strong>Monitor (p=none):</strong> Start here. Add rua to receive reports. Run for 2-4 weeks.</li>
            <li><strong>Analyze:</strong> Check reports for legitimate services failing authentication.</li>
            <li><strong>Fix:</strong> Add SPF records and DKIM keys for all legitimate senders.</li>
            <li><strong>Quarantine (p=quarantine):</strong> Move to quarantine for 1-2 weeks after fixing issues.</li>
            <li><strong>Reject (p=reject):</strong> Final enforcement. Best protection against spoofing.</li>
          </ol>
        </div>
      )}

      {warnings.length > 0 && (
        <div className="space-y-1.5">
          {warnings.map((w, i) => (
            <div key={i} className={`flex items-start gap-2 text-xs ${w.type === "warning" ? "text-amber-700 dark:text-amber-400" : "text-blue-600 dark:text-blue-400"}`}>
              <span className="mt-0.5 shrink-0">{w.type === "warning" ? "!" : "i"}</span>
              <span>{w.text}</span>
            </div>
          ))}
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Policy (p=)</label>
          <select
            value={policy}
            onChange={(e) => setPolicy(e.target.value as typeof policy)}
            className="w-full rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-50"
          >
            <option value="none">None (monitor only) â€” Start here</option>
            <option value="quarantine">Quarantine (spam folder) â€” Intermediate</option>
            <option value="reject">Reject â€” Maximum protection</option>
          </select>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Subdomain Policy (sp=)</label>
          <select
            value={spPolicy}
            onChange={(e) => setSpPolicy(e.target.value as typeof spPolicy)}
            className="w-full rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-50"
          >
            <option value="">Same as p=</option>
            <option value="none">None</option>
            <option value="quarantine">Quarantine</option>
            <option value="reject">Reject</option>
          </select>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">DKIM Alignment (adkim=)</label>
          <select
            value={adkim}
            onChange={(e) => setAdkim(e.target.value as typeof adkim)}
            className="w-full rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-50"
          >
            <option value="">Relaxed (default) â€” Subdomains match</option>
            <option value="s">Strict â€” Exact domain match required</option>
            <option value="r">Relaxed â€” Subdomains accepted</option>
          </select>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">SPF Alignment (aspf=)</label>
          <select
            value={aspf}
            onChange={(e) => setAspf(e.target.value as typeof aspf)}
            className="w-full rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-50"
          >
            <option value="">Relaxed (default)</option>
            <option value="s">Strict â€” Exact domain match required</option>
            <option value="r">Relaxed â€” Subdomains accepted</option>
          </select>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label htmlFor="dmarc-rua" className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Aggregate Reports (rua)</label>
          <Input id="dmarc-rua" type="email" value={rua} onChange={(e) => setRua(e.target.value)} placeholder="dmarc-reports@example.com" />
          <p className="mt-1 text-[11px] text-zinc-600 dark:text-zinc-300">Receives daily XML reports</p>
        </div>
        <div>
          <label htmlFor="dmarc-ruf" className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Forensic Reports (ruf)</label>
          <Input id="dmarc-ruf" type="email" value={ruf} onChange={(e) => setRuf(e.target.value)} placeholder="forensic@example.com" />
          <p className="mt-1 text-[11px] text-zinc-600 dark:text-zinc-300">Receives per-failure details</p>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Percentage (pct=)</label>
          <Input type="number" min={1} max={100} value={pct} onChange={(e) => setPct(e.target.value)} />
          <p className="mt-1 text-[11px] text-zinc-600 dark:text-zinc-300">Apply policy to X% of email</p>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Failure Options (fo=)</label>
          <select
            value={fo}
            onChange={(e) => setFo(e.target.value as typeof fo)}
            className="w-full rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-50"
          >
            <option value="">Not set</option>
            <option value="0">Generate if SPF/DKIM both fail</option>
            <option value="1">Generate if either fails</option>
            <option value="d">Generate if DKIM fails</option>
            <option value="s">Generate if SPF fails</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <Button variant="secondary" size="sm" onClick={resetForm}>Reset All</Button>
        <button type="button" onClick={() => setShowAdvanced(!showAdvanced)} className="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400">
          {showAdvanced ? "Hide" : "Show"} advanced format options
        </button>
      </div>

      <div className="overflow-hidden rounded-xl border border-zinc-200 dark:border-zinc-800">
        <div className="flex items-center justify-between border-b border-zinc-200 bg-zinc-50 px-5 py-3 dark:border-zinc-800 dark:bg-zinc-900">
          <p className="text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Generated DMARC Record (<span className="font-mono">TXT</span>)</p>
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={handleCopy}>{copied ? "Copied!" : "Copy"}</Button>
            <Button variant="secondary" size="sm" onClick={handleDownloadTxt}>Download</Button>
          </div>
        </div>
        <div className="px-5 py-4">
          <pre className="overflow-x-auto whitespace-pre-wrap break-all text-sm text-zinc-900 dark:text-zinc-50">{
            record.length > 0
              ? `${record};`
              : "Configure options above to generate a DMARC record."
          }</pre>
        </div>
      </div>

      {showAdvanced && (
        <div className="rounded-xl border border-zinc-200 bg-zinc-50 px-5 py-4 dark:border-zinc-800 dark:bg-zinc-900">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">DNS Zone Entry (BIND format)</p>
          <pre className="mb-3 overflow-x-auto text-sm text-zinc-700 dark:text-zinc-300">_dmarc  IN  TXT  "{record};"</pre>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">Verify with dig</p>
          <pre className="mb-3 overflow-x-auto text-sm text-zinc-700 dark:text-zinc-300">dig TXT _dmarc.example.com +short</pre>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500 dark:text-zinc-400">DMARC Tag Reference</p>
          <table className="w-full text-xs text-zinc-600 dark:text-zinc-400">
            <thead><tr className="border-b border-zinc-200 dark:border-zinc-700"><th className="px-2 py-1 text-left font-medium">Tag</th><th className="px-2 py-1 text-left font-medium">Required</th><th className="px-2 py-1 text-left font-medium">Description</th></tr></thead>
            <tbody>
              <tr className="border-b border-zinc-200 dark:border-zinc-700"><td className="px-2 py-1">v=DMARC1</td><td className="px-2 py-1">Yes</td><td className="px-2 py-1">Version (must be DMARC1)</td></tr>
              <tr className="border-b border-zinc-200 dark:border-zinc-700"><td className="px-2 py-1">p=</td><td className="px-2 py-1">Yes</td><td className="px-2 py-1">Policy: none, quarantine, reject</td></tr>
              <tr className="border-b border-zinc-200 dark:border-zinc-700"><td className="px-2 py-1">sp=</td><td className="px-2 py-1">No</td><td className="px-2 py-1">Subdomain policy (defaults to p=)</td></tr>
              <tr className="border-b border-zinc-200 dark:border-zinc-700"><td className="px-2 py-1">pct=</td><td className="px-2 py-1">No</td><td className="px-2 py-1">Percentage of email to filter (1-100)</td></tr>
              <tr className="border-b border-zinc-200 dark:border-zinc-700"><td className="px-2 py-1">rua=</td><td className="px-2 py-1">No</td><td className="px-2 py-1">Aggregate report URI (mailto:)</td></tr>
              <tr><td className="px-2 py-1">adkim=</td><td className="px-2 py-1">No</td><td className="px-2 py-1">DKIM alignment: r=relaxed, s=strict</td></tr>
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
